### PR TITLE
white color text clearly visible now

### PR DESCRIPTION
**Pull request by himanshujaidka**
Screenshot (41)

### CODE REVIEW

**Comment by anushbhatia** [comment]
text in light mode is not visible now

**Comment by smaranjitghose** [comment]
> text in light mode is not visible now

@himanshujaidka @anushbhatia meant that since you changed the color of the text to white for dark mode, it is now invisible in normal mode

**Comment by himanshujaidka** [comment]
you have to refresh the page
for that

**Comment by himanshujaidka** [comment]
after refreshing we are able to see white text

**Comment by anushbhatia** [comment]
Why should u refresh for that?

**Comment by smaranjitghose** [comment]
> after refreshing we are able to see white text
I am aware of that 😅
This is the current deploy of your changes: https://deploy-preview-50--doc2pen.netlify.app/editor.html

**Comment by himanshujaidka** [comment]
yes please guide me on how I could achieve this without refreshing the page?

**Comment by himanshujaidka** [comment]
yes @anushbhatia you are right user doesn't want to refresh the page so how I could achieve this

**Comment by anushbhatia** [comment]
Try having state for dark mode text and light mode text or u can di that using jquery by (textarea).removeclass(white-text).addclass(black-text) ; something like this but prefer using css for it using dark mode clour for text.

**Comment by himanshujaidka** [comment]
I have made another PR in this all the bugs which I mentioned above is solved but we have to refresh the page another bug arises 😅

**Comment by anushbhatia** [comment]
Ok i will take care for this

**Pull request closed without merging**
