### PR TITLE
Vertical navbar links

### PR DESCRIPTION
**Pull request by MennaMagdy2019**
I made links Vertical using flex-direction: column; on small screens

Can you review my issue, please? @smaranjitghose  @anushbhatia

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Nice work. On hover the sidebar should extend over the entire screen.

Reference: https://girlscriptboilerplate.smaranjitghose.com/

**Comment by smaranjitghose** [comment]
Also, please incorporate the recent changes and fix the merge conflicts

**Comment by MennaMagdy2019** [comment]
I don't know where is the merge conflict 
Can you tell me, please? @smaranjitghose

**Comment by MennaMagdy2019** [comment]
I made the change in the new branch and fixed the merge conflicts
Can you review it @smaranjitghose

**Pull request closed without merging**
