### PR TITLE
added border to the page

### PR DESCRIPTION
**Pull request by sahebsunny**
Added 6 images in pages
edited editor.js
edited editor.html

and sir in editor.html there ware 2 choosePage(6) it should be 7 in the parameter I corrected it

### CODE REVIEW

**Comment by anushbhatia** [comment]
great work @sahebsunny 🙌. It's perfect from my side

**Comment by sahebsunny** [comment]
Thank you Sir for your review
 it was for DWOC
What I need to do for it to get merge

> great work @sahebsunny 🙌. It's perfect from my side
@anushbhatia 
Thank you Sir for your review
 it was for DWOC
What I need to do for it to get merge

**Comment by smaranjitghose** [comment]
> Thank you Sir for your review
> it was for DWOC
> What I need to do for it to get merge
> 
> > great work @sahebsunny 🙌. It's perfect from my side
> > @anushbhatia
> > Thank you Sir for your review
> > it was for DWOC
> > What I need to do for it to get merge

Can you please pull the current changes and fix the merge conflict

**Comment by sahebsunny** [comment]
> > Thank you Sir for your review
> > it was for DWOC
> > What I need to do for it to get merge
> > > great work @sahebsunny 🙌. It's perfect from my side
> > > @anushbhatia
> > > Thank you Sir for your review
> > > it was for DWOC
> > > What I need to do for it to get merge
> 
> Can you please pull the current changes and fix the merge conflict

Ok sir I am making a new Pr for this

**Pull request closed without merging**
