### PR TITLE
Need review for g-drive integration

### PR DESCRIPTION
**Pull request by himanshujaidka**

### CODE REVIEW

**Comment by himanshujaidka** [comment]
@smaranjitghose please tell me that how could I generate the URL of the downloaded image so that it will automatically save to drive

**Comment by smaranjitghose** [comment]
> @smaranjitghose please tell me that how could I generate the URL of the downloaded image so that it will automatically save to drive

Please spend some time on stackoverflow, reading some blogs before shooting the queries. I just gave a feedback on this a few hours ago

**Comment by anushbhatia** [comment]
Add this to the navbar

**Comment by himanshujaidka** [comment]
okay

**Comment by imsahil007** [comment]
> okay

@himanshujaidka  go through this link 
https://developers.google.com/drive/api/v3/quickstart/js

**Pull request closed without merging**
