### PR TITLE
Fixed bug in Media-manip page

### LINKED ISSUE #874: Bug: Media Manip
### Bug detail : 
- Input and Output dropdown holds the value of previous file even after removing the file.

---
### Gif explaining the bug :
doc2pen_issue

---

### The fix :
- The input and output dropdown should be changed to default after removing the file from the drag and drop box.

### PR DESCRIPTION
**Pull request by SandeepKrSuman**
> Fixes #874 

- Resolved the issue of input/output field holding the value of previous selected file even after removing the file.
- Changed two files in order to resolve the issue
- Sent setOutput() state function as a prop from MediaManip.jsx
- Inside DragDrop.jsx, used the deleteImage event to change the value of input/output field to default

### Issue Resolved :
doc2pen_resolved

### CODE REVIEW

**Review by ashuvssut — COMMENTED** [review]
resolve merge conflict

**Comment by SandeepKrSuman** [comment]
I've resolved the conflicts. Take a look

**Review by ashuvssut — APPROVED** [review]

**Review by ashuvssut — APPROVED** [review]
wait for project maintainers to review and merge you changes🙂

**Comment by bijankundu** [comment]
@SandeepKrSuman  When converting multiple types of files, the input type is mentioned as "MIX"  but after removing a single image from the drag and drop section, the input type changes to its default value, which should not happen. I guess, it should either keep the input type as "MIX" (if there are multiple file type) or keep the input type as the file type(in case of a single file)

https://user-images.githubusercontent.com/50210712/115114271-07dc4700-9fac-11eb-805f-4b4513bc6df4.mp4

**Comment by SandeepKrSuman** [comment]
Hi @bijankundu , Thanks for pointing the issue. I have worked on it. Do take a look

**Comment by SandeepKrSuman** [comment]
Also the app is running fine on my local machine, but here it is showing some checks were not successful. I've no idea why checks are failing here whereas it is working fine locally. 

P.S : I squashed my commits as there were lot of them and hence I had to force push to my branch.

**Review by bijankundu — APPROVED** [review]

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
