### PR TITLE
Scrollbar.

### PR DESCRIPTION
**Pull request by padmajabhol**
Screenshot (28)
Added a custom scrollbar.

### CODE REVIEW

**Review by Harshita-Kanal — COMMENTED** [review]
Looks good 👍

**Comment by padmajabhol** [comment]
> Looks good 👍 

Will it be merged?

**Review by anushbhatia — CHANGES_REQUESTED** [review]
1. Add the same to the editor too
2. Also the fill colour can be made a bit darker so that the bar is easily visible.

🎉🎉Great Work Hoping to see more contribution from your end.

**Comment by anushbhatia** [comment]
Do add the same on the editor page in the next PR.

**Comment by padmajabhol** [comment]
> Do add the same on the editor page in the next PR.

I tried it on styles.modules.css file inside the editor section, even after enabling overflow-y, it didn't work. Tried to do the same inside all css files in the editor section and it wasn't working. Could you please tell me the specific css file where I should implement it. Pardon me, I m new to all of this.

**Comment by anushbhatia** [comment]
> > Do add the same on the editor page in the next PR.
> 
> I tried it on styles.modules.css file inside the editor section, even after enabling overflow-y, it didn't work. Tried to do the same inside all css files in the editor section and it wasn't working. Could you please tell me the specific css file where I should implement it. Pardon me, I m new to all of this.

sure contact me on discord will guide you through it.

**Comment by smaranjitghose** [comment]
Nice work @padmajabhol

**Pull request merged**
