### PR TITLE
Navbar improved

### PR DESCRIPTION
**Pull request by varunvj1**
# Description
Added a navigation bar 

## Fetaures
<ul>
<li> Added dark theme toggle button
<li> Toggle working fine for <b>editor page </b> and <b> navbar </b>
</ul>

## Issue
The components of the page (like footer, cards) are being worked on by other participants, so I feel its better to implement dark mode at the end when the design part is final, else the code will have to be changed again and again for dark mode depending on the class names used for making other components.

## Screenshots 
Dark mode
light mode

### CODE REVIEW

**Comment by anushbhatia** [comment]
on hover change the color of text blue instead of the whole link

**Comment by varunvj1** [comment]
Made the requested change.

**Comment by smaranjitghose** [comment]
> Made the requested change.

@varunvj1 Can you please try to fix the merge conflict. And I am closing your previous PR, since the final changes are in this one

**Comment by varunvj1** [comment]
Please check if the conflicts resolved were correct. I saw a lot of new code while resolving issues.

**Pull request closed without merging**
