### PR TITLE
Open Source cards updated

### PR DESCRIPTION
**Pull request by satyampandeygit**
Issue - #297 solved

### CODE REVIEW

**Review by anushbhatia — APPROVED** [review]
Just a suggestion if u can prevent the logo from spreading or stretching it would be great rest the PR is perfect

**Comment by satyampandeygit** [comment]
Okay I will look into it

**Comment by satyampandeygit** [comment]
I changed the logo's but SWOC logo gets faded every time. what I should do?

**Comment by smaranjitghose** [comment]
Please name them appropritatly.
--> DevScript Winter of Code 2020
--> Script Winter of Code 2021

**Comment by smaranjitghose** [comment]
> I changed the logo's but SWOC logo gets faded every time. what I should do?

Use [this](https://swoc.tech/img/logo-2.png) one please

**Comment by satyampandeygit** [comment]
I did the changes as said, no change in swoc logo now also. We need to change the background.

**Comment by smaranjitghose** [comment]
> I did the changes as said, no change in swoc logo now also. We need to change the background.

Ya. We need to change the background of the logo.

**Comment by satyampandeygit** [comment]
I have changed the background

**Comment by satyampandeygit** [comment]
I am participant in SWOC I didn't saw the logo, will this be counted?

**Comment by smaranjitghose** [comment]
> I am participant in SWOC I didn't saw the logo, will this be counted?

No worries. I'll request the team to consider this. But from next time, contribute after the bonding period

**Comment by satyampandeygit** [comment]
Thanks :)

**Pull request merged**
