### PR TITLE
Addition of features to the Home Page (Issue: Home Page)

### PR DESCRIPTION
**Pull request by Aniruddhmuley2001**
This pull request solves the Issue#56 of the project.

Following Features have been added to the home page:
1) The home page is now responsive (especially the cards which were broken in the mobile view).
2) The video player now supports all the browsers and can autoplay accordingly.
3) On scrolling, effects have been added to the illustrations and text content.
4) Hover functionality on the cards has been improved, keeping in mind the theme followed by the page.
5) In the end, a button has been added to redirect to "Check out the Editor", after the user explores the page.

Libraries used here are:
1) Bootstrap: For the ease of responsiveness and design features.
2) Animate on Scroll: To provide effects to the content on scroll.
3) Video.js: To provide an interface to play video across all browsers and flawlessly.

### CODE REVIEW

**Comment by anushbhatia** [comment]
Don't change the font family let it remain the same and video is optimized to a great extent

**Comment by Aniruddhmuley2001** [comment]
> Don't change the font family let it remain the same and video is optimized to a great extent

So, should the font family be restored to the original version? Also, the issue mentioned changes required in the video, which before was not supporting Firefox, and now supports all platforms. Please do clarify these doubts.

**Comment by smaranjitghose** [comment]
Good work @Aniruddhmuley2001 .

- Can you please have a look at the merge conflict and try to fix it?
- Also can you put the check it out button just before the features?
respon
- Also there's a slight issue in the mobile view, try to debug this.

**Comment by smaranjitghose** [comment]
Also, try to replace the video with a zoomed gif like this https://www.prco.com/ and a corresponding animation

**Comment by Aniruddhmuley2001** [comment]
Merging the conflicts completed for this version. On the second point, normally we see the checkout button at the end (before the maintainers and contributors section). So I wish to know your thought process of adding the checkout Editor button before the features, though it is already present on the navbar. Also, I will definitely try to resolve other issues and work on your suggestions.

**Comment by anushbhatia** [comment]
okay sure continue with other issues will take care of that thing

**Comment by Aniruddhmuley2001** [comment]
I have solved the above issues and included the suggestions mentioned above in another pull request, being pull request #89. Please do review the PR.

**Comment by Aniruddhmuley2001** [comment]
Also, should this PR be closed, or the tags will be the same for the other PR?

**Comment by smaranjitghose** [comment]
> Also, should this PR be closed, or the tags will be the same for the other PR?

Ya

**Pull request closed without merging**
