### PR TITLE
Uniformheadings

### PR DESCRIPTION
**Pull request by lakshita15**
Made all the text and headings uniform and responsive.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Resolve the conflict

**Comment by smaranjitghose** [comment]
Only the headings were required and not the text/subheadings.

**Comment by lakshita15** [comment]
i did ask @anushbhatia  and generated pr when he said yes. Pls reassign i'll only change headings and undo the others.

**Comment by lakshita15** [comment]
Also i'll resolve issues.

**Comment by smaranjitghose** [comment]
> i did ask @anushbhatia and generated pr when he said yes. Pls reassign i'll only change headings and undo the others.

Cool. Assigned for 1 more day

**Comment by lakshita15** [comment]
is the font style poppins ok?

**Comment by smaranjitghose** [comment]
> is the font style poppins ok?

Ya.

**Comment by lakshita15** [comment]
Can i haave your discord username or do the convversation here ?

**Comment by smaranjitghose** [comment]
> Can i haave your discord username or do the convversation here ?

Please use the doc2pen channel for discussion as other mentors/maintainer can help you with the same if I am not available at any moment

**Pull request closed without merging**
