### PR TITLE
download options added

### PR DESCRIPTION
**Pull request by mharshita**
Fixes: #271 
Download options added as png, jpg, jpeg and pdf.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> Fixes: #271
> Download options added as png, jpg, jpeg and pdf.

Can you upload a clip of the working please @mharshita . When I tried it was trying to save the HTML content

**Comment by mharshita** [comment]
> > Fixes: #271
> > Download options added as png, jpg, jpeg and pdf.
> 
> Can you upload a clip of the working please @mharshita . When I tried it was trying to save the HTML content

Yes Sir. It is not working yet. Actually, the output window does not load on localhost, that's why I made a PR and converted it to draft to work on this issue, So that I can see the changes on deploy-preview. Please give me some more time to resolve the issue.

**Comment by smaranjitghose** [comment]
> > > Fixes: #271
> > > Download options added as png, jpg, jpeg and pdf.
> > 
> > 
> > Can you upload a clip of the working please @mharshita . When I tried it was trying to save the HTML content
> 
> Yes Sir. It is not working yet. Actually, the output window does not load on localhost, that's why I made a PR and converted it to draft to work on this issue, So that I can see the changes on deploy-preview. Please give me some more time to resolve the issue.

No worries. Take your time

**Comment by mharshita** [comment]
@smaranjitghose Please review.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Please review.

We have to look into the encoding for the pdf file, the image formats work fine

**Comment by mharshita** [comment]
> > @smaranjitghose Please review.
> 
> We have to look into the encoding for the pdf file, the image formats work fine

Okay!

**Pull request merged**
