### PR TITLE
icon-pack4 : devices and hardware icons

### LINKED ISSUE #668: Add device related icons to the Sketch Page
## Sample Icons
mobile_icons

## Requirements:

- Do not mess up any other part of the web app
- Add an icon on the horizontal menu, on clicking which a drop down/another bar appears below showing options for icons representing laptops, pc, phones, etc which can be imported as a shape like the other ones
- Add up to 10 different icons
- Please test this thoroughly before giving a PR
- Make use of any open source icons (or make custom icons) for this. You are required to give references in the PR description.

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #668 

added dropdown + icons

icons fetched from 
-  https://www.svgrepo.com/vectors/device/ 
- https://www.flaticon.com/packs/smart-devices?k=1615927940770 
- https://freeicons.io/material-icons-file-3/devices-icon-17364 

image

---------------------------------
_- I have participated in GSSOC and CrossWoC_

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Try keeping those icons that look more like hand-drawn icons and have similar design for coloured and non coloured icons present there

**Comment by ashuvssut** [comment]
update: I can find hand-drawn svgs for devices. so i have added simple svgs instead that anyone can draw with ease

image

**Review by anushbhatia — CHANGES_REQUESTED** [review]
1. Keep bold bordered ones together
2. cpu and gpu should be together having similar design.
3. thin line svgs should also be kept in another pack

**Comment by anushbhatia** [comment]
Great resolve the conflict will merge this

**Pull request merged**
