### PR TITLE
editor page

### PR DESCRIPTION
**Pull request by mharshita**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@anushbhatia Can you please review this one?

**Comment by mharshita** [comment]
@smaranjitghose sorry this is still in draft..... i dont know how the label got removed....

**Comment by smaranjitghose** [comment]
> @smaranjitghose sorry sir this is still in draft..... i dont know how the label got removed.... Please give me some more time to work on it

Cool

**Comment by mharshita** [comment]
@smaranjitghose  @anushbhatia  I have made the editor page. Please review.
There are some major bugs:-
- The image of page to show the output is still not visible
- The responsive view
Please give some time to fix them

**Comment by mharshita** [comment]
image
image

**Comment by smaranjitghose** [comment]
More updates are required

**Comment by mharshita** [comment]
> More updates are required

okay sir

**Pull request merged**
