### PR TITLE
Added Import from .doc Option

### PR DESCRIPTION
**Pull request by sahebsunny**

### CODE REVIEW

**Comment by sahebsunny** [comment]
sir, I did it in two Pr as you told me to in #269

**Comment by sahebsunny** [comment]
sir, it's working but sometimes some RTF may show up. I tried to remove as much I could, If I tried more to remove the RTF it may effect the document
But right now it's able to collect the text from the docs ( if it contains RTF just backspacing will delete it)

**Comment by sahebsunny** [comment]
This contains the RTF
Screenshot 2021-01-06 at 7 18 52 PM

But if scroll down

Screenshot 2021-01-06 at 7 19 15 PM


After backspacing got the text
Screenshot 2021-01-06 at 7 19 31 PM

**Comment by smaranjitghose** [comment]
> sir, it's working but sometimes some RTF may show up. I tried to remove as much I could, If I tried more to remove the RTF it may effect the document
> But right now it's able to collect the text from the docs ( if it contains RTF just backspacing will delete it)

When we shift to REACT completely, this can be dealt with

**Pull request merged**
