### PR TITLE
fixes #445. change x-axis

### LINKED ISSUE #445: REACT:Editor Bug🐛
Change default x-axis to 10 instead of 5

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #445

image

-- DWoC and SWoC participant

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Rescale the values

The scale on display starting from 5 does not make sense w.r.t ux

It should ideally be starting from 0

**Review by smaranjitghose — APPROVED** [review]

**Comment by ashuvssut** [comment]
okay

**Comment by smaranjitghose** [comment]
> okay. I ll do it

Create separate issues for all!

**Comment by ashuvssut** [comment]
image

**Comment by ashuvssut** [comment]
sir this is from codepen

**Comment by smaranjitghose** [comment]
> sir this is from codepen
> it looks very ordinary.
> 
> can i make a cool one for it? you would definitely like it
Arrey! 🤣 Don't just stop at first few pens.  There are tons there.

This is [404 ](https://portfolio.smaranjitghose.codes/lol) page we have for the awesome-portfolio-website.

Something of the similar accord

Feel free to use your creativity

**Comment by ashuvssut** [comment]
http://blessnbliss.org/404.html

**Comment by smaranjitghose** [comment]
> http://blessnbliss.org/404.html

Yes, if you can do that animation it would be fantastic!

keep in mind:
- We have to make it with the name "Doc2pen"
- Follow the color scheme to the best possible variation
- Have a button to re-direct the user to the home page

**Comment by ashuvssut** [comment]
it takes png and svg to make those particles

**Comment by ashuvssut** [comment]
it doesnt take words or letters

**Comment by ashuvssut** [comment]
i can go to wix.com and then select a logo for doc2pen.

then I will show you

**Pull request merged**
