### PR TITLE
Header updated

### PR DESCRIPTION
**Pull request by Akshit42-hue**
I have made some changes in Style.css

### CODE REVIEW

**Comment by smaranjitghose** [comment]
This does not solve the highlighted issue

**Comment by Akshit42-hue** [comment]
@smaranjitghose can you please give some more detail about the issue

**Comment by smaranjitghose** [comment]
> @smaranjitghose can you please give some more detail about the issue

I have given a snapshot and pointed out the difference. Please refer it there

**Comment by Akshit42-hue** [comment]
@smaranjitghose  so basically in the website at the home page t is not seeing properly right this is the issue

**Comment by smaranjitghose** [comment]
> @smaranjitghose so basically in the website at the home page t is not seeing properly right this is the issue

ya

**Pull request closed without merging**
