### PR TITLE
REACT: Added Home Page

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue: #357 

I have added Home Page in `src/pages/HomePage`.

doc2pen

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
@anushbhatia Please check the file structure

**Comment by sanjay270899** [comment]
@smaranjitghose Let me know if any changes needed.

And please change the label from `SWoC2021` to `DWOC` and `Level-x`.

Thank you!

**Review by anushbhatia — CHANGES_REQUESTED** [review]
1. Image location should be modified  src/assets/images for team images
2. Use black colour everwhere for the colour scheme in header footer and main gradient on home page too.

**Review by anushbhatia — COMMENTED** [review]
Don't use the same template as the current project. Create each component from scratch and then we can proceed each element along with it.

**Comment by sanjay270899** [comment]
> Don't use the same template as the current project. Create each component from scratch and then we can proceed each element along with it.

What do you mean by **from scratch**?

**Comment by sanjay270899** [comment]
> 1. Image location should be modified  src/assets/images for team images
> 2. Use black colour everwhere for the colour scheme in header footer and main gradient on home page too.

@anushbhatia Ok, I am fixing point 1. But point 2 is invalid. Refer #357 . I was told to make it similar to basic HTML, CSS, and JS website version.

**Comment by smaranjitghose** [comment]
> > 1. Image location should be modified  src/assets/images for team images
> > 2. Use black colour everwhere for the colour scheme in header footer and main gradient on home page too.
> 
> @anushbhatia Ok, I am fixing point 1. But point 2 is invalid. Refer #357 . I was told to make it similar to basic HTML, CSS, and JS website version.

I guess what @anushbhatia means is you have exactly copy pasted the css and js from the base version and rendered it into react components and pages. It was required to have a similar UI but not the same messy code

**Comment by sanjay270899** [comment]
@smaranjitghose Please check once again. It was not just a copy/paste work. I have spent more than half of my day to migrate the whole HomePage to React.

**Comment by sanjay270899** [comment]
image

Here, in Home Section, previously bootstrap was used for CSS. Whereas I have used my own custom CSS.

I agree that I have copied CSS from the base branch in many places because I want to make the HomePage look simliar to the basic version of the website.

@smaranjitghose 
And please tell me, in which Component did you find the messy code?

**Comment by sanjay270899** [comment]
@smaranjitghose and @anushbhatia at least reply.

**Comment by anushbhatia** [comment]
Convert the complete theme to black and white colours.

**Comment by sanjay270899** [comment]
@anushbhatia example?

**Comment by anushbhatia** [comment]
https://leerob.io/

**Comment by sanjay270899** [comment]
@anushbhatia It will be better if this is done in a separate issue.

**Comment by anushbhatia** [comment]
Ok then do it after i merge this PR

**Pull request merged**
