### PR TITLE
 icon-pack3 : speech bubbles

### LINKED ISSUE #669: Add Speech Bubble related Icons to Sketch Page
## Sample Icons
conversation_icons

## Requirements:

- Do not mess up any other part of the web app
- Add an icon on the horizontal menu, on clicking which a drop down/another bar appears below showing options for icons representing common chat bubbles
- Add up to 10 different icons
- Please test this thoroughly before giving a PR
- Make use of any open source icons (or make custom icons) for this. You are required to give references in the PR description.

## General PR Guidelines:

- The title of the PR is short and meaningful
- You refer to the respective issue in the PR description ``Resolves # issue_number``
- Attach screenshot(s)/clip of the result of your changes
- (In bullet points) describe your changes

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #669 

added dropdown + icons

icons fetched from 
- https://www.svgrepo.com/svg/82688/thought-bubble 
- https://freesvg.org/speech-bubble 

image

---------------------------------
_- I have participated in GSSOC and CrossWoC_

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Keep the bubble size big so that the person can add relevant text to that and also maintain uniformity by keeping similar bubbles together in one pack.

**Comment by ashuvssut** [comment]
These are svgs. so these can be resized like those arrow icon we have (currently present in our sketch toolbox)

svgs wont blur when scaled. when putting these on the canvas I will make sure that user can resize them

**Comment by anushbhatia** [comment]
> These are svgs. so these can be resized like those arrow icon we have (currently present in our sketch toolbox)
> 
> svgs wont blur when scaled. when putting these on the canvas I will make sure that user can resize them

Sure but they don't look similar to a single-family. The only ones I like are 1,6,7 cause they are more related to the project.

**Comment by ashuvssut** [comment]
ok

i ll try to find

**Comment by ashuvssut** [comment]
update

image

**Comment by anushbhatia** [comment]
keep the last two and give the PR.

**Comment by ashuvssut** [comment]
Hello @anushbhatia 

This repo do not follow any "indentation rule"
we should tell contributors to use indentation of 2 spaces (via contributing.md)

because of this issue, solving merge conflicts is a messy task

Please open up a issue for a contributing.md update -- and -- I think I will replace all the indentation from 4 to 2 in my future PRs (eventually 😅). so, no need to open up a issue for that. And... when merging PRs...do check for indentation changes. tell them to use a indentation of 2 spaces

**Pull request merged**
