### PR TITLE
Sketch Dark Mode

### LINKED ISSUE #546: Sketch: Dark Mode
I would Like to add Dark Mode Functionality.

### PR DESCRIPTION
**Pull request by sanjay270899**
Closes #546 

- Added Sketch Dark Mode Functionality

1. Light Mode
image

2. Dark Mode
image

### CODE REVIEW

**Comment by smaranjitghose** [comment]
AHH.. As far as the UI goes, it's dope

But logically speaking, if we introduce a dark mode one would have take extra efforts in order to get similar results to that of the light mode ( I mean the output of the sketches)

We can rather have an option to change the background to make this simple.

@anushbhatia @sanjay270899 what do you think?

**Comment by sanjay270899** [comment]
> But logically speaking, if we introduce a dark mode one would have take extra efforts in order to get similar results to that of the light mode ( I mean the output of the sketches)

Extra Efforts like?

> change the background to make this simple.

Yeah, I will build this in future PR soon.

@smaranjitghose

**Comment by sanjay270899** [comment]
I think you are confused with background. Currently the background is transparent. So, downloading image drawn in light and dark mode will be same. (And about the background, it is already in my todo.)

**Comment by sanjay270899** [comment]
@smaranjitghose You got my point?

**Comment by smaranjitghose** [comment]
> 
> 
> @smaranjitghose You got my point?

Yep! I do understand.
### Try the following please:
- Switch to dark mode for the sketch page
- Set the pen color to Black
- And draw atleast 7 sqaures one after the other (in progession)

I observe an expected change in background color to different shades of pink (magenta to be specific).

You can give it a try [here](https://deploy-preview-550--doc2pen.netlify.app/sketch) for convinience

**Comment by sanjay270899** [comment]
@smaranjitghose I didn't get you. Can you please provide me the screenshot?

**Comment by smaranjitghose** [comment]
### Stage 1
stage1

### Stage 2
stage_2

### Stage 3
stage_3

### Stage 4
stage_4

### Stage 5
stage_5

### Stage 6
stage_6

**Comment by sanjay270899** [comment]
@smaranjitghose How? 😅

chrome-capture (2)

**Comment by sanjay270899** [comment]
@smaranjitghose Are you using any extension? How can the color change!

Background color is given with CSS. It has nothing to do with Canvas.

**Comment by sanjay270899** [comment]
@smaranjitghose Maybe due to some extension in your browser it is coming like that. I have checked in `Chrome` as well as in `Edge`, also my friend has also tried this, But back ground color is not changing.

Background Color has been given by CSS. It has nothing to do with canvas.

**Comment by smaranjitghose** [comment]
> 
> 
> @smaranjitghose Maybe due to some extension in your browser it is coming like that. I have checked in `Chrome` as well as in `Edge`, also my friend has also tried this, But back ground color is not changing.
> 
> Background Color has been given by CSS. It has nothing to do with canvas.

Ya, just checked my Firefox has an option to prevent canvas fingerprinting. It was weirdly interrupting with this.

**Pull request merged**
