### PR TITLE
improved maintainer's UI

### LINKED ISSUE #674: Improve Project Maintainer UI @Home Page
## Requirements

- Try to have a swish effect like the cards in [this](https://www.hellomonday.com/about)
- Below the pictures, put the respective names 
- Below the names put the Github and Linkedin icons
-  Use [microanimations](https://useanimations.com/) for the social media icons
- Try your level best to have the images change on click (as in the reference above). 
- The images (max of 3 for each card), text, link to social media should be loaded dynamically from the team.js as the current codebase does
- DO NOT mess up any other part of the web app you are not dealing with

## General PR Guidelines:

- The title of the PR is short and meaningful
- You refer to the respective issue in the PR description ``Resolves # issue_number``
- Attach screenshot(s)/clip of the result of your changes
- (In bullet points) describe your changes

### PR DESCRIPTION
**Pull request by Mukulikaa**
1. Added fade-up effect with AOS package
2. Added microanimations with lottie-react-web package
3. Brought names and social media links below card instead of inside
Resolves #674 

Doc2pen

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image

**Comment by Mukulikaa** [comment]
Woah that's weird. I'll fix it.

**Comment by Mukulikaa** [comment]
image

I am unable to pinpoint the problem because it looks fine on my screen. Can you help me?

**Review by anushbhatia — COMMENTED** [review]
I have attached the resolution too just check that.
image

**Comment by smaranjitghose** [comment]
contributor_ui
Please read the requirements of the issue carefully. This PR does not meet any of them

**Pull request closed without merging**
