### PR TITLE
Sketch: Text Feature

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #547 

- Added Text Feature

1. Font Size
2. Font Color
3. Font Style
4. Font Family

**GIF**

textFeature_547

(Spent my whole night)

### CODE REVIEW

**Comment by sanjay270899** [comment]
Resolving Merge Conflicts. I thought my previous PR will get reject.

**Comment by smaranjitghose** [comment]
> 
> 
> Resolving Merge Conflicts. I thought my previous PR will get reject.

Naah.. If you have worked hard to contribute something meaningful, we would definitely integrate it. It's just that at times as maintainers we need to be double sure about the changes to avoid future fallouts 😄

**Comment by smaranjitghose** [comment]
Just tag me once done.

**Comment by sanjay270899** [comment]
@smaranjitghose Done.

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
