### PR TITLE
Sketch: Fill Pattern

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #547

Fill Pattern Feature

### CODE REVIEW

**Comment by sanjay270899** [comment]
image

**Comment by smaranjitghose** [comment]
Improve the UI to something like a button which says "Import Custom Pattern"

**Review by smaranjitghose — APPROVED** [review]

**Comment by sanjay270899** [comment]
> Improve the UI to something like a button which says "Import Custom Pattern"

Sure.

**Comment by sanjay270899** [comment]
> Improve the UI to something like a button which says "Import Custom Pattern"

@smaranjitghose Sure.

**Pull request merged**
