### PR TITLE
added functionality to newsletter in footer

### PR DESCRIPTION
**Pull request by AbhipsaGuru1012**
Issue: #401
Added functionality to the subscription form in footer.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/40017559/106333947-b4613380-62af-11eb-8741-c9816594ebf6.mp4
it is not working locally

**Comment by AbhipsaGuru1012** [comment]
@anushbhatia I tested on my local machine and it's working fine. Please make sure to run the backend server alongside the frontend. Also make sure to provide the correct credentials in index.js file in backend and change the 'from' section of the mail to a valid email id. After clicking on subscribe button after 2-3seconds you will be able to see the alert message. If there is any error you can check it out on the backend console.

https://stackoverflow.com/questions/19877246/nodemailer-with-gmail-and-nodejs
Please refer to the above link to make changes to the gmail account to allow less secure apps. Refer to the second solution.

**Comment by smaranjitghose** [comment]
> @anushbhatia I tested on my local machine and it's working fine. Please make sure to run the backend server alongside the frontend. Also make sure to provide the correct credentials in index.js file in backend and change the 'from' section of the mail to a valid email id. After clicking on subscribe button after 2-3seconds you will be able to see the alert message. If there is any error you can check it out on the backend console.
> 
> https://stackoverflow.com/questions/19877246/nodemailer-with-gmail-and-nodejs
> Please refer to the above link to make changes to the gmail account to allow less secure apps. Refer to the second solution.
> 
> [ alert ](url)
> This alert message will be displayed after the message is sent

We are deploying this on netlify. So I guess the proxy value of local host won't work

**Comment by AbhipsaGuru1012** [comment]
@smaranjitghose I have modified package.json. Please check if it is working now because it is working fine on my local machine. Also I think we will have to deploy the backend because we are using the link in axios.

**Comment by AbhipsaGuru1012** [comment]
> > @anushbhatia I tested on my local machine and it's working fine. Please make sure to run the backend server alongside the frontend. Also make sure to provide the correct credentials in index.js file in backend and change the 'from' section of the mail to a valid email id. After clicking on subscribe button after 2-3seconds you will be able to see the alert message. If there is any error you can check it out on the backend console.
> > https://stackoverflow.com/questions/19877246/nodemailer-with-gmail-and-nodejs
> > Please refer to the above link to make changes to the gmail account to allow less secure apps. Refer to the second solution.
> > [ alert ](url)
> > This alert message will be displayed after the message is sent
> 
> We are deploying this on netlify. So I guess the proxy value of local host won't work

@smaranjitghose I also removed the alert message that gets displayed after subscribing to a text that says 'Successfully Subscribed!'

subscribe1

Please review.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Major problem is that we are really sorry to do this but we can't use nodejs for a different server
https://dev.to/itnext/setting-up-a-news-letter-with-react-and-mailchimp-2f6p
we will rely on something like this for now.
In case we want this code push it on a new branch in this

**Comment by AbhipsaGuru1012** [comment]
> Major problem is that we are really sorry to do this but we can't use nodejs for a different server
> https://dev.to/itnext/setting-up-a-news-letter-with-react-and-mailchimp-2f6p
> we will rely on something like this for now.
> In case we want this code push it on a new branch in this

@anushbhatia should I make changes and add the functionality using mailchimp?

**Comment by smaranjitghose** [comment]
> > Major problem is that we are really sorry to do this but we can't use nodejs for a different server
> > https://dev.to/itnext/setting-up-a-news-letter-with-react-and-mailchimp-2f6p
> > we will rely on something like this for now.
> > In case we want this code push it on a new branch in this
> 
> @anushbhatia should I make changes and add the functionality using mailchimp?

Yes

**Pull request closed without merging**
