### PR TITLE
changes made in contibutors section

### PR DESCRIPTION
**Pull request by raksha009**
issue #59

### CODE REVIEW

**Comment by raksha009** [comment]
My pr is not able to pass Checkpoint 1 (It says integration failed). What does it mean and how to rectify it?

**Comment by smaranjitghose** [comment]
> My pr is not able to pass Checkpoint 1 (It says integration failed). What does it mean and how to rectify it?
> Also, plz review my PR
> 
> ezgif com-optimize

We have more number of contributors to a project compared to project maintainers (Let's say around 50). So it's not feasible to have such large cards with 3D animations.

Try something similar to the "Our Team" section as done [here](https://www.madstreetden.com/about-us/)

**Comment by smaranjitghose** [comment]
Please name the css classes more legibly..not like ``contri``😅 and try to comment on the new sections you add in the CSS or even in the html files more elaborately. It's a good developer practice

**Comment by raksha009** [comment]
ezgif com-optimize

**Comment by smaranjitghose** [comment]
@raksha009 
# Congratulations on getting your first Pull request merged!

<p align = "center"></p>

You forgot to add yourself as a contributor 😉

**Comment by raksha009** [comment]
Thank you 😁  yeahh😅

**Pull request merged**
