### PR TITLE
New PR: Provided styling to the elements in the contact and the editor page

### PR DESCRIPTION
**Pull request by prateekkk26**

### CODE REVIEW

**Comment by anushbhatia** [comment]
I think white looks better currently. @smaranjitghose what about you

**Comment by smaranjitghose** [comment]
Yes, if it was some buttons on the canvas itself, this would have been nice but for a menu bar having another color for the interior components looks a bit weird

**Comment by prateekkk26** [comment]
I will try to fix that and make the necessary changes so that the colors on the page don't look off from each other.

**Comment by smaranjitghose** [comment]
Closing due to inactivity

**Pull request closed without merging**
