### PR TITLE
Add Tech Stack related Icons to Sketch Page

### PR DESCRIPTION
**Pull request by ashuvssut**
This PR is the base of all the icon-pack issues created my @anushbhatia 

### Functioning
I have created a library-page that uses `webpack` to dynamically include all svgs present in a `icon-pack` folder

after collecting those icons ...they just get populated the library-page

---------------------------------------

**NOTE**: I have just created the Library. **these icons cant be used in the sketch page right now.** I will give PR for that soon

> This PR doesnt close/fix any Issue. It is the base feature that all contributors will need when putting their new icons.

-----------------------
_- I have participated in GSSOC_

### CODE REVIEW

**Comment by ashuvssut** [comment]
image

image

**Comment by smaranjitghose** [comment]
@ashuvssut Please do not add this a separate option. This should beside the other icons and on clicking, a drop down or another bar should appear below (with a similar icon size)

**Comment by smaranjitghose** [comment]
> @ashuvssut Please do not add this a separate option. This should beside the other icons and on clicking, a drop down or another bar should appear below (with a similar icon size).

**Comment by smaranjitghose** [comment]
Pardon me @ashuvssut. I have changed the requirements of the issue (made it simpler). Please have a look and give a new PR. The issue shall remain assigned to you unless you wish to discontinue

**Pull request closed without merging**
