### PR TITLE
 Preloader Animation Completed!

### PR DESCRIPTION
**Pull request by vedant-jain03**
I have changed preloader animation as mentioned in the issue by @smaranjitghose
->used pen , logo for animations.
->changed the color of the pen to sea green as mentioned in the issue.
->Responsive

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Could you increase the transition time by a couple of seconds. Currently, the website loads even before it's complete

**Comment by vedant-jain03** [comment]
@smaranjitghose thankyou so much for reviewing PR sir, I got your point. But I have one doubt that I have initialize the transition to infinite but I think the loading is under <Suspense > component means the loading is managed by suspense component.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Keep the background lighter in colour so that the animation looks soothing. Currently there are two blues one on each other

**Comment by smaranjitghose** [comment]
Closed due to inactivity

**Pull request closed without merging**
