### PR TITLE
Make button functional and also align.

### PR DESCRIPTION
**Pull request by raman-thakur**
Following changes, I have done

1. Button is now functional and it redirects to the Editor page.
2. Button was not aligned properly I have aligned that.

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
w.r.t to the top section could you please center align the text and the button

**Comment by raman-thakur** [comment]
Done sir i have updated that, pls give your feedback!

**Comment by raman-thakur** [comment]
is everything ok to merge in my PR??? @smaranjitghose

**Comment by smaranjitghose** [comment]
@raman-thakur could you just incorporate the recent changes so that I can merge your PR

**Comment by raman-thakur** [comment]
> @raman-thakur could you just incorporate the recent changes so that I can merge your PR

sir, This is my first time in Open source can you pls explain what I need to do pls...??

**Comment by smaranjitghose** [comment]
> > @raman-thakur could you just incorporate the recent changes so that I can merge your PR
> 
> Following changes, I have done:
> 
> 1. Button is now functional and it redirects to the Editor page.
> 2. Button was not aligned properly I have aligned that.
> 3. heights and widths of images and text area were not properly designed I have made them well.
> 
> sir, This is my first time in Open source can you pls explain what I need to do next so that my PR will get merged @smaranjitghose ??

@raman-thakur brother your PR is perfect w.r.t to the requirements. 

My previous comment implied that while your PR was being reviewed, a couple of other PRs were also merged that dealt with Banner.Js and Banner.module.css so there was an issue with commit history not matching

The ideal way to resolve this is to pull the changes from my(upstream) repo to your(forked) repo. Here I am implying main branch.  Create the feature branches and add the changes that you proposed via this PR


Anyways, try that out next time as a homework ( i hope😅) I merging this PR for now

**Comment by raman-thakur** [comment]
Sir i didn't got DWOC label, i am participating in DWOC 2021 @smaranjitghose

**Pull request merged**
