### PR TITLE
add stroke+fill color

### LINKED ISSUE #767: Add Line Color and Fill Color Options
## Snapshot

Sketch_Color

## Description

Currently, the sketch feature allows one to have either hollow or solid shapes. We intend to improve upon this by splitting the color feature to have:

- Line Color (Color of the strokes/boundaries of the figures)
- Fill Color (Color of the region enclosed by the figures in case the Fill Option is selected)

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #767 

image

------------------------------
_- I have participated in GSSOC and CrossWoC_

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@ashuvssut brother, the stroke opacity is not required as of now, we can simply do with the color and width feature

**Comment by ashuvssut** [comment]
image

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Nice work @ashuvssut

**Comment by ashuvssut** [comment]
> Nice work @ashuvssut
> 
thankyou  😁😁

**Pull request merged**
