### PR TITLE
Responsive contact page added

### PR DESCRIPTION
**Pull request by Adyasha8105**
I have added a **responsive contact page** with an appropriate name and classes.
@smaranjitghose Have a look.

ss: 
image

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> I have added a **responsive contact page** with an appropriate name and classes.
> @smaranjitghose Have a look.
> 
> ss:
> image

@Adyasha8105 Please have a look at the issue, I have mentioned multiple times that it should be a section in the index.html as we are doing a single page website

**Comment by Adyasha8105** [comment]
> > I have added a **responsive contact page** with an appropriate name and classes.
> > @smaranjitghose Have a look.
> > ss:
> > image
> 
> @Adyasha8105 Please have a look at the issue, I have mentioned multiple times that it should be a section in the index.html as we are doing a single page website

Sorry, sir my fault.
Here, I have added the contact page content and also solved the **footer bug** (which takes time to figure it).

bug:-
image

**Comment by smaranjitghose** [comment]
Some small changes:
-Reduce the size of input area for the Name, Email, Phone Number, Subject. Increase it for the message

**Comment by smaranjitghose** [comment]
> Some small changes:
> -Reduce the size of input area for the Name, Email, Phone Number, Subject. Increase it for the message

Remove Phone Number and Email. Simply put the map of India (use API)  on the right

**Pull request merged**
