### PR TITLE
added character count feature

### PR DESCRIPTION
**Pull request by himanshujaidka**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> _No description provided._

@himanshujaidka We need a word count feature. So if an average word is 7 letters long, so if we allow 10000 words (i.e. a length of medium story). it should be 70,000 letters and note we have not taken into account the whitespace. Please fix this. And only provide word count, if you want to. Showing Character count is not of much use.

A simple logic for word count will be:

```
- Check if there are two or more consecutive spaces(replace that by one)
- Count number of comma(s)
- Count number of fullstop(s)
-  Count number of semi-colon(s)
- Count the number of spaces
- Sum them the above
- add 1(for the last word)
- Now for every fullstop ('.') or comma(',') or semicolon(';') followed by a space reduce the count by one.
   
    Eg: I am a dedicated, practical and collaborative developer
```

A reference to a similar (yet incomplete implementation is): https://www.w3resource.com/javascript-exercises/javascript-regexp-exercise-6.php

Please document your code more

**Comment by smaranjitghose** [comment]
words_shit
 Do not put this a separate tab, just but it below the input area. Check out how we have it for twitter

**Comment by smaranjitghose** [comment]
Don't forget to link the Issue Numbers

**Comment by himanshujaidka** [comment]
ok got this @smaranjitghose

**Comment by smaranjitghose** [comment]
@himanshujaidka any updates?

**Pull request closed without merging**
