### PR TITLE
Update editor.html

### PR DESCRIPTION
**Pull request by prateek1998**
Xaxis slider bug fixed

you are doing great work..

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Doc2Pen and 16 more pages - Personal - Microsoft​ Edge 24-08-2020 16_51_51
Change this too

**Comment by prateek1998** [comment]
I didn't understand what you are trying to say

**Comment by smaranjitghose** [comment]
> Doc2Pen and 16 more pages - Personal - Microsoft​ Edge 24-08-2020 16_51_51
> Change this too

1) The canvas is not mobile responsive
2) The line spacing slider

**Comment by smaranjitghose** [comment]
@prateek1998 If you are still working on this please give another PR with the requested changes

**Pull request closed without merging**
