### PR TITLE
Added a sketch functionality.

### PR DESCRIPTION
**Pull request by bhoomika07**
Screenshot 2021-01-04 at 3 45 14 PM
 1. This is how the sketch page looks like. The paint tab is added in the navigation bar for all the pages.
 2. It allows you to change the pen color, size toggle pan, add basic shapes like square, circle, and triangle.
 3. Scalable text box can be added.
 4. Images can be uploaded, objects can be grouped or ungrouped.
 5. Redraw allows you to clear the entire drawing area and save allows you to save in a png format.

Screenshot 2021-01-04 at 3 51 34 PM
sketch (10)
 
I have sent a video working of the same on slack channel of awesome portfolio websites because the file limit exceeded here.
thanks, 
carbseater & bhoomika07

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
@bhoomika07 please fix the merge conflicts

**Comment by smaranjitghose** [comment]
@anushbhatia can you please give design improvements for this so that @carbseater can take over

**Comment by carbseater** [comment]
@smaranjitghose I'm working under Devscript winter of code, so can you add this label DWOC? Or if doesn't matter then its fine 👍

**Comment by smaranjitghose** [comment]
> @smaranjitghose I'm working under Devscript winter of code, so can you add this label DWOC? Or if it doesn't matter then its fine 👍

Done

**Comment by bhoomika07** [comment]
> @bhoomika07 please fix the merge conflicts

done

**Pull request merged**
