### PR TITLE
changes done

### PR DESCRIPTION
**Pull request by srishtimaggo15**
done

### CODE REVIEW

**Comment by srishtimaggo15** [comment]
donne

**Comment by srishtimaggo15** [comment]
Nav bar, footer and other changes done

**Review by shreyakapoor08 — CHANGES_REQUESTED** [review]
@srishtimaggo15 Kindly mention properly in the PR template about what all changes you have done in the PR along with the screenshot showing the changes.
Update that.
Also resolve the merge conflicts.

**Comment by smaranjitghose** [comment]
Have a look at the current version of the website and the issues. Your work is many commits behind

**Comment by srishtimaggo15** [comment]
Sure I will look into it and do the commits. Sent from Mail for Windows 10 From: Smaranjit GhoseSent: 11 September 2020 14:26To: smaranjitghose/doc2penCc: Srishti Maggo; MentionSubject: Re: [smaranjitghose/doc2pen] changes done (#139) Have a look at the current version of the website and the issues. Your work is many commits behind—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by srishtimaggo15** [comment]
> @srishtimaggo15 Kindly mention properly in the PR template about what all changes you have done in the PR along with the screenshot showing the changes.
> Update that.
> Also resolve the merge conflicts.
Okay I show you here what changes I have made.
Screenshot (983)
Screenshot (984)

I made changes in the nav bar , the logo and other fonts and also made the footer section.

**Pull request closed without merging**
