### PR TITLE
#646 Done - Contact Us Component is Shifted to Bottom of the Home Page

### PR DESCRIPTION
**Pull request by nijin26**
Issue No. #646 

Moved the contact component from pages section to Home Page as a section.
2_contact

I have provided a heading and created a nav link in side navigation.
1__contact

### CODE REVIEW

**Comment by smaranjitghose** [comment]
contact_section
Please remove this and give a simple centre aligned heading "Get in Touch".

Rest looks fine!

**Comment by nijin26** [comment]
"Get in Touch" , Heading added

**Comment by smaranjitghose** [comment]
@nijin26 I am merging the PR this time. From next time onwards, please ensure you do a squash commit of your changes for all the PRs as described in the Contributing.MD

**Review by smaranjitghose — APPROVED** [review]

**Comment by nijin26** [comment]
@smaranjitghose Really sorry for making 2 PRs. My Windows got crashed and that made me fork repo again (due to some reasons) and do the balance commits from linux.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Really sorry for making 2 PRs. My Windows got crashed and that made me fork repo again (due to some reasons) and do the balance commits from linux.

It's fine brother. Just keep in mind the feedback given above for the upcoming PRs 😄

**Pull request merged**
