### PR TITLE
eraser fixed

### PR DESCRIPTION
**Pull request by shruthii625**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@shruthii625 

One suggestion ( Though I am much more involved with machine learning work than web development):

Try to keep the indentation of the conditionals and functions in each script as clean as possible

```
if  ( ){
     .
     .
     .
     }
else if ()
    {
     .
     .
     .
     }
```

Rest looks fine😎

**Comment by sanjay270899** [comment]
Still I will say that it is not a nice solution. Try `clearRect()`, may be this will be a better solution.

**Comment by shruthii625** [comment]
> @shruthii625
> 
> One suggestion ( Though I am much more involved with machine learning work than web development):
> 
> Try to keep the indentation of the conditionals and functions in each script as clean as possible
> 
> ```
> if  ( ){
>      .
>      .
>      .
>      }
> else if ()
>     {
>      .
>      .
>      .
>      }
> ```
> 
> Rest looks fine😎

The if-else statements in this entire project followed this convention so I followed it too. I'll keep this in mind the next time I do changes!

**Comment by shruthii625** [comment]
@sanjay270899 You can open an issue related to the eraser then. I'll work on it when I have time!

**Comment by sanjay270899** [comment]
@shruthii625 I was just suggesting.

See how image will look like after downloading:
image

**Comment by shruthii625** [comment]
@sanjay270899 yeah, I realised xD
I'll re-implement it using clearRect()

**Pull request closed without merging**
