### PR TITLE
404 page done

### LINKED ISSUE #452: create a 404 page and also set its route
I want to create a nice **interactive** 404 page for our doc2pen webapp

I once created [this](http://blessnbliss.org/404.html) page. I want use that interactive particles to create the 404 page.

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #452 

Here in this page, the logo might look lame but My brother was able to create this last version of the logo which is better than previous two. all the three versions are present in `src/assests/` folder.

I think that the logo can be improved further in this 404 page. So, we should create a issue to get a better logo design.
Desktop-Recording-5
<gif above: 5mb>
**P.S** we should keep the logo width <=360px (to fit all screen sizes) the logo size cant be dynamically resized and drawn into particle slider `canvas` element

_--I have participated in DWoC SWoC and MWoC_

---------------------------
user=ashuvssut:score=

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> closes #452
> 
> Here in this page, the logo might look lame but My brother was able to create this last version of the logo which is better than previous two. all the three versions are present in `src/assests/` folder.
> 
> I think that the logo can be improved further in this 404 page. So, we should create a issue to get a better logo design.
> Desktop-Recording-5
> <gif above: 5mb>
> **P.S** we should keep the logo width <=360px (to fit all screen sizes) the logo size cant be dynamically resized and drawn into particle slider `canvas` element
> 
> -- DWoC SWoC and MWoC participant

Ideally, the 404 page is a standalone page. So we make it quite different from the other pages. Also, there is no navbar but a button to go back to the Home Page of the web app

**Comment by smaranjitghose** [comment]
Text Animation is not visible @ashuvssut

**Comment by smaranjitghose** [comment]
Put some relevant illustrations in the background

**Comment by ashuvssut** [comment]
> Text Animation is not visible @ashuvssut

sir in deploy view that animation is not showing for some reason. In deploy view preloader color is also not white. it is black

**Comment by ashuvssut** [comment]
image
those emoji colors are not visible in the screen shot. I dont know why its not capturing its yellow color.

**Comment by smaranjitghose** [comment]
@anushbhatia some suggestions w.r.t the background?

I would suggest something more appealing like [1](https://dribbble.com/shots/9288196-404-Don-t-Move-Fast)

**Comment by ashuvssut** [comment]
currently the background is a dynamic one ( svg animation ). 

Sir, if you want you would love to see a static svg instead, then I have to use any other static svg (i.e, not the same one that was used in that dribble example you gave)

**Comment by ashuvssut** [comment]
currently the background is a dynamic one ( svg animation ).

Sir, if you want you would love to see a static svg instead, then I have to use any other static svg (i.e, not the same one that was used in that dribble example you gave).

I have to look for one that looks simple with less borders or dark lines( just to keep that main doc2pen interactive logo clearly visible). If there is more lines/background under the particles, then it wont look right. it will look cluttered. so I will have to keep that static svg just under the text area.

@anushbhatia If you have any suggestion then please add😁😁

**Comment by smaranjitghose** [comment]
> currently the background is a dynamic one ( svg animation ).
> 
> Sir, if you want you would love to see a static svg instead, then I have to use any other static svg (i.e, not the same one that was used in that dribble example you gave).
> 
> I have to look for one that looks simple with less borders or dark lines( just to keep that main doc2pen interactive logo clearly visible). If there is more lines/background under the particles, then it wont look right. it will look cluttered. so I will have to keep that static svg just under the text area.
> 
> @anushbhatia If you have any suggestion then please add😁😁

Yes, use a static svg like one in the example, then we can animate it later.

Also, the text is not at all visually attractive. Use GOTHAM, change the color to black

Avoid using a single color for the entire page

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Reorganize the assets in this PR as per the current structure please

**Comment by smaranjitghose** [comment]
Tweak the routing.

The current one loads 404 as `doc2pen.netlify.app/oops`. Make it 404 and not `oops` 😅

Do these changes, I'll integrate this into the project since we currently don't have a 404. In a follow-up PR, continue with 404 UI page enhancements

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
