### PR TITLE
404 UI

### LINKED ISSUE #511: Improve 404 page UI
### **Feel free to work as per your ideas. We do not have any specifications for this.**

- You can take inspirations from platforms like Dribble, Codepen, etc but **DO NOT COPY PASTE THE EXACT THING**
- Make sure the routing is not messed up
- Try out if the 404 functionality is working before giving the PR

The issue is self-explanatory given one has read the above points. Looking forward to your design tweaks!

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #511 

Presenting you my very own creativity😁😁 with a svg from undraw. I chose this svg coz it was simple and had no borders. It wont conflict with particles. 

It is better than some previous versions I tried. All looked dirty. so I thought to pick a very simple svg with bright background.
So, This the end product. Its clean and simple
https://deploy-preview-549--doc2pen.netlify.app/oops

--------------
_--I have participated in DWoC SWoC and MWoC_

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
The Colour contrast in the background is too bright. Try using colours from google and see mix and match. Also, the illustration should be a right coloured one if u are using a dark bg.

**Comment by ashuvssut** [comment]
It would be great if you could provide me some color hex codes that I can use

Anyways, I will see n change the colors n update it now

**Comment by anushbhatia** [comment]
https://www.behance.net/gallery/63446079/RED-VIKING-Packaging-Visual-Communication
https://dribbble.com/shots/5303963-Mariama

**Comment by ashuvssut** [comment]
from google I picked 2 colors

blue #4285F4 (shirt color)
yellow #F4B400 (background)

google's green color did look good as a "background". I used spotify's green #1DB954. you can try those and check. spotify's green suits well

google's blue was too light and didnt fit well for logo's color. So I put the best one from colorhunt.co that matched well.

For logo I found that having dark shades make the particles look like dirt
so i kept it as it is. I have put some extra logo shades (in assets/images/404/) to try on. you can also try those. But, I have put the best one

**Comment by ashuvssut** [comment]
instead of

"lets go back"

how about

"lets go home"
?

since we are taking the user to home page... 'home' word suits well😅

And also the dialogue is like "You are lost buddy! You went too far... Let's go home"😛

**Comment by anushbhatia** [comment]
Try using only one colour then

**Comment by ashuvssut** [comment]
image
can set particles as white...or dark color...(particles are thin)
The particles dont fit well if there is a background under them
**The background under particles must be simple solid color.**


image

So text area and particles area must be totally separate

**Comment by ashuvssut** [comment]
> Try using only one colour then

ok i will use a single dark color

**Comment by ashuvssut** [comment]
before
image
image

after
image

**Comment by smaranjitghose** [comment]
> 
> 
> before
> image
> image
> 
> after
> image

Quick Tip: unless you have a picture in the background, try to ensure that the text does not overlap with the elements of the illustration in layer behind

**Comment by smaranjitghose** [comment]
- Try to alter the font, it is not at all going well with the background
- Remove the logo. We can't have both a big logo and illustration. It looks weird

**Comment by ashuvssut** [comment]
if i remove the logo...where should i implement my particles then?

**Comment by smaranjitghose** [comment]
Deploy preview is failing @ashuvssut

**Comment by ashuvssut** [comment]
I have removed the logo made up of particles

do you want the other type of particles instead.... i mean the particles used in awesome-portfolio home page?

**Comment by ashuvssut** [comment]
@smaranjitghose ignore these commits.

I am going to start again with a simple layout

**Comment by ashuvssut** [comment]
i will be pushing a new 404 page today in this same branch

**Comment by anushbhatia** [comment]
Background merges with the illustration and the design is not up to the mark

**Comment by ashuvssut** [comment]
@anushbhatia  this tym I have put a simple 404 page with 
- animated text
- animated button(hover effect)
- animated emoji(svg)

**Comment by anushbhatia** [comment]
Change let's go home to go back

**Comment by ashuvssut** [comment]
Done

**Pull request merged**
