### PR TITLE
Sketch Shapes Draw Feature

### LINKED ISSUE #474: Sketch Page Enhancements
# Tasks:

- Format and prettify(I don't imply the extension) the menu/tool bar further with dedicated buttons named "Pen Color", "Pen Width", "Export"
- Increase the canvas size slightly for larger screens
- Have a floating docker on the canvas or maybe options in the menu/tool bar for usual shapes like square, rectangle, circle, ellipse, triangle, diamond, arrow like [this](https://excalidraw.com/)
- Opacity, Stroke, and Fill Settings for the shapes

## Some more specification(s):

- For the stroke style, we need an option for going back to the usual stroke style ( ___) from the other two
- Keep the opacity only for the fill color and not the boundary of the shapes
- For the Fill Color, try to add an option for selecting the color using color picker
- It would be great if you could add some descriptive icons(like Stroke Style, Stroke Width, Opacity, Fill Color, Stroke Color ) so that the menu bar is easy to understand

##### Take up one task at a time.

### PR DESCRIPTION
**Pull request by sanjay270899**
Closes #474 

- Line
- Square
- Circle
- Triangle
- Arrow
- Diamond

shapesDraw_474

Currently not focusing on design. I am thinking to first build some basic features then I will improve the design of the sketch.

### CODE REVIEW

**Comment by ashuvssut** [comment]
how did you create that gif so small in dimensions? did you recorded the screen and then converted it to gif? or do you use some extension?

**Comment by sanjay270899** [comment]
> how did you create that gif so small in dimensions? did you recorded the screen and then converted it to gif? or do you use some extension?

https://microsoftedge.microsoft.com/addons/detail/click-to-capture/jmiocoejabdcdefolopebbhnkgnohgco?hl=en-US

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
One suggestion: Make the arrow similar to the line so that we can have it in any direction by selecting it once. For changing direction(across an axis I mean), if we have to select another arrow button and continue, it would be less comforting while creating UML diagrams.

@anushbhatia Do you have any suggestions for the icons? perhaps something like feathericons?

**Comment by smaranjitghose** [comment]
> > how did you create that gif so small in dimensions? did you recorded the screen and then converted it to gif? or do you use some extension?
> 
> https://microsoftedge.microsoft.com/addons/detail/click-to-capture/jmiocoejabdcdefolopebbhnkgnohgco?hl=en-US

I am glad to see if we have such discussions beyond just individual contributions! Kudos to all of you

**Comment by sanjay270899** [comment]
@smaranjitghose Yes, that will be nice. I will improve it along with my other PR.

**Pull request merged**
