### PR TITLE
Solved issue #299

### PR DESCRIPTION
**Pull request by Amit366**
I have updated the style.css file with a soothing hover effect.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> I have updated the style.css file with a soothing hover effect.

The effect works fine. Can you choose a color that complements the gradient of the navbar more than the current red one

**Comment by Amit366** [comment]
Sir should I use black or dark blue?

**Comment by smaranjitghose** [comment]
> Sir should I use black or dark blue?

@anushbhatia can guide you with UI/UX more efficiently than me. Can you please drop him a text

**Comment by Amit366** [comment]
@anushbhatia can u suggest me on the  hover colour

**Review by anushbhatia — COMMENTED** [review]
In my opinion, convert the navbar into a single colour rather than this gradient and then we can apply hover effect because the current navbar colours are pretty faded and they don't add a catchy effect to eye it would be pretty great if you choose a better blue and add that to the site.
Then for the hover effect, u can use white colour and that would be pretty decent I thing.

**Comment by anushbhatia** [comment]
Dark colours don't suit it either have a complete black template or keep it bright and catching

**Comment by Amit366** [comment]
Uploading hover effect.mp4…

Sir is this design ok?

**Comment by Amit366** [comment]
https://user-images.githubusercontent.com/60662775/103434633-4979f980-4c2a-11eb-8803-f63e400fe0e8.mp4

Sir is this design ok?

**Comment by smaranjitghose** [comment]
Can you please fix the merge conflicts by pulling the merge conflicts?

**Comment by Amit366** [comment]
Yes sir done

**Comment by Amit366** [comment]
The program is DWOC

**Comment by Amit366** [comment]
Sir should I make any other changes??

**Comment by Amit366** [comment]
Sir please accept my PR

**Comment by smaranjitghose** [comment]
> Sir please accept my PR

Have a look at the preview of your PR [here](https://deploy-preview-321--doc2pen.netlify.app/)

The home page is quite messed up

**Comment by Amit366** [comment]
sir on my laptop its working fine

**Comment by smaranjitghose** [comment]
>  hover.effect.mp4 
> Sir is this design ok?

You have not pulled the recent changes I believe.
In your video, the bug for the top section space is still there but for the recent version it's fixed

**Comment by Amit366** [comment]
so should I close this pull request and again send another PR

**Comment by smaranjitghose** [comment]
> so should I close this pull request and again send another PR

Ya

**Pull request closed without merging**
