### PR TITLE
add dependabot

### LINKED ISSUE #1015: Dependecy Bot 🤖
Creating a bot that automatically updates the dependencies.
https://dependabot.com/
link to the website is attached

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #1015

### CODE REVIEW

**Comment by ashuvssut** [comment]
@anushbhatia what is your time preference to get the dependabot PRs?

- weekly - 10am - sunday
- daily - 10am
- Give your own preference

We can also add more update configs like this. checkout (this link)[https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore]

I have put the important configs. But we can add more if we need

Validate the dependabot.yml code [here](https://dependabot.com/docs/config-file/validator/) when needed

**Comment by ashuvssut** [comment]
more configs are available

- [versioning-strategy](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#versioning-strategy)

**Comment by anushbhatia** [comment]
weekly will be fine

**Comment by ashuvssut** [comment]
done

**Pull request merged**
