### PR TITLE
Improvement of Contact-Us Done

### PR DESCRIPTION
**Pull request by ShubhamSj07**
**Updated Validations** of contact-us form with proper error messages
Doc2Pen_ContactUs-Validations

Added Goodbye Card which will be shown after successfully submitting of form
Doc2Pen_GoodBye_Card

Also, card will be responsive in all screen-sizes!
Also fixed the page reload issue in contact-us form!

### CODE REVIEW

**Comment by ShubhamSj07** [comment]
@smaranjitghose , pls review pr!

**Comment by anushbhatia** [comment]
Deploy is failing, create a new PR and also use a minimal colour of red so that blue and red match.

**Comment by smaranjitghose** [comment]
@anushbhatia Could you please suggest a better scheme for the font and the text colors. The red over violet background is somewhat weird

**Comment by ShubhamSj07** [comment]
> @anushbhatia Could you please suggest a better scheme for the font and the text colors. The red over violet background is somewhat weird

@smaranjitghose, but the errors should be thrown in red color to follow standards, right?

**Comment by anushbhatia** [comment]
if you want to follow the standards then change the background to a minimal colour.

**Pull request closed without merging**
