### PR TITLE
Generated all kinds of pages mentioned under "Choose Page" dropdown

### PR DESCRIPTION
**Pull request by Jahnavi-Jonnalagadda**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
page_error

**Comment by Jahnavi-Jonnalagadda** [comment]
@smaranjitghose, should we wait for @anushbhatia to review and then work on the changes?

**Comment by smaranjitghose** [comment]
The issue I pointed out above still persists

**Comment by Jahnavi-Jonnalagadda** [comment]
I'm unable to generate the handwritten content after I choose a file

**Pull request closed without merging**
