### PR TITLE
icon-pack2 : stick-figures

### LINKED ISSUE #671: Add Stick Figure related icons to Sketch Page
## Sample Icons
stick_icons

## Requirements:

- Do not mess up any other part of the web app
- Add an icon on the horizontal menu, on clicking which a drop down/another bar appears below showing options for icons representing stick figures
- Add up to 10 different icons
- Please test this thoroughly before giving a PR
- Make use of any open source icons (or make custom icons) for this. You are required to give references in the PR description.

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #671 

added dropdown + icons

icons fetched from https://svgsilh.com/tag/stickman-1.html

image

---------------------------------
_- I have participated in GSSOC and CrossWoC_

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Try adding all similar kind of stick figure this looks like mix of stick figures keep the uniformity across the complete pack.

**Comment by anushbhatia** [comment]
In stick figure light the last icons is not a part of that illustration set. 
Dark ones the first 2 are a bit off.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
remove the 4,5,7 from them too

**Comment by ashuvssut** [comment]
> remove the 4,5,7 from them too

which pack? thin or bold?

**Comment by anushbhatia** [comment]
Light

**Comment by ashuvssut** [comment]
image

**Comment by ashuvssut** [comment]
image

**Pull request merged**
