### PR TITLE
Changes to Contributors List

### LINKED ISSUE #642: Modify Contributor Section @Home Page
image

## Requirements
- Make the cards of the contributors round in shape(add border radius)
- Reduce the size of the cards so that all 65 contributors' details can easily be accomodated

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

### PR DESCRIPTION
**Pull request by malavikarajeshvikraman**
-  Added Border radius to contributors profile images
- Now  all contributers are visible in the homepage 

Resolves #642

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
## Feedback:

- The PR meets majority of the requirement(s). Nice work @malavikarajeshvikraman !
- Increase the grid size or reduce the size of the cards so that in each row we can have 8-10 cards

**Comment by anushbhatia** [comment]
Also, remove the names (instead keep the GitHub icon to it)or reduce the font size of the name.

**Comment by malavikarajeshvikraman** [comment]
Screenshot 2021-03-17 063114

-  Reduced Size of Cards
- Removed names and now there is Github icon there.

**Comment by anushbhatia** [comment]
GitHub is not completely centre aligned check that and do it rest everything is fine.

Great Work🎉🎉✨✨. Hoping for more contribution from you.

**Comment by malavikarajeshvikraman** [comment]
-  I have made the social media icon to center

**Comment by malavikarajeshvikraman** [comment]
@anushbhatia  Thank you ! I will look for more issues to contribute to.

**Pull request merged**
