### PR TITLE
Set up Pre-Commit Hooks

### LINKED ISSUE #1016: Set up Pre-Commit Hooks
Use Husky

Reference(s):

- [1](https://dev.to/botreetechnologies/setting-up-husky-pre-commit-hook-with-eslint-prettier-and-lint-staged-for-react-and-react-native-d05) # Read the comments as well for getting around some possible errors
- [2](https://markoskon.com/create-a-pre-commit-hook-with-husky-and-lint-staged/)

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #1016

This PR's changes depend on .prettierrc.js that will come from PR #1021

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
First Resolve #1022  then this

**Comment by ashuvssut** [comment]
@anushbhatia, I was working on an issue. In that, i wanted to use react-draggable package. so I installed it.

But when i ran `yarn start` again, there was a weird error.
In stackoverflow I found out that it was caused by useing 2 package managers in one single project (npm and yarn).

so i removed my node_modules folder and both the lock files. Then i re installed packages using yarn only. now everything works fine

This PR has that changes

**Comment by ashuvssut** [comment]
After recent pull, there was a problem with packages. I googled the error and came to know that it was because of using more than package managers (npm and yarn). Thats why Deploy preview failed

Now I have clean installed all packages using yarn. The problem with packaged is gone

**Comment by ashuvssut** [comment]
@smaranjitghose  resolving these right away. just a sec

**Comment by ashuvssut** [comment]
@smaranjitghose, bhaiya Merge conflict resolved!

**Pull request merged**
