### PR TITLE
Experience form UI

### PR DESCRIPTION
**Pull request by Tanya933**
Improved the UI of experience-form in the Contact Us page.

### CODE REVIEW

**Comment by Tanya933** [comment]
improved the UI of the experience-form.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Overflow issue here and last emoji is overlapping with text

**Comment by smaranjitghose** [comment]
@Tanya933 please do a squash commit

**Comment by Tanya933** [comment]
ok i will do the necessary changes @smaranjitghose and @anushbhatia

**Comment by Tanya933** [comment]
Screenshot 2021-03-15 at 10 58 32

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Still, the responsiveness issue is there.
also, the text fields should have the same font as the one used in the heading of the form

**Comment by Tanya933** [comment]
@anushbhatia Thankyou for reviewing .I am working on it

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
just move it a little up and the placeholder's font should be the same as the text as heading

**Review by anushbhatia — APPROVED** [review]

**Comment by anushbhatia** [comment]
Resolve the conflict

**Comment by smaranjitghose** [comment]
The responsiveness issue still persists.
Please raise a new PR (and do a single squash commit)

**Pull request closed without merging**
