### PR TITLE
[feature] New contact page

### PR DESCRIPTION
**Pull request by ashuvssut**
In this PR:

- made a  new page for the contact us section and updated navbar and routing.
- I have put Footer in app.js and removed from all pages (home, editor, etc). So no need to add it manually in every page
- Restyled the map components

**XTRA FEATURE**🤩🤩: I added a Layers feature on Map. It enables the visitor to view map in different themes

**EDIT:**

- Revamped contact us form

- **XTRA** added SEO also😁😁

---------------
_--I have participated in DWoC SWoC and MWoC_

### CODE REVIEW

**Comment by sanjay270899** [comment]
@ashuvssut I think you forgot to remove Contact Quick Link from Quick Box from Header.

**Comment by smaranjitghose** [comment]
> 
> 
> @ashuvssut I think you forgot to remove Contact Quick Link from Quick Box from Header.

Along with that some more improvements:
- Adjust the background color of the heading above to suit the theme of the page. The current white one appears weird
- Just make the text "Get in touch"
- In the web view, the form is too much squeezed. A [similar reference](https://girlscriptboilerplate.netlify.app/contactus)

**Comment by ashuvssut** [comment]
I will be pushing new changes in a minute

**Comment by ashuvssut** [comment]
Revamped contact us form

**XTRA** added SEO also😁😁

**Comment by smaranjitghose** [comment]
For the map functionality I am merging this PR, however the UI needs more improvement

**Comment by ashuvssut** [comment]
image

which part can be improved?

**Pull request merged**
