### PR TITLE
Added 7 fonts

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
#61 
Added 7 fonts using Calligraphr.
@anushbhatia @smaranjitghose 
ss-1
ss-2

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Can you please attach the screenshots of all the seven fonts

**Comment by Bhavya-Sehgal** [comment]
ss-3
ss-4
ss-5
ss-6
ss-7

**Comment by Bhavya-Sehgal** [comment]
Added screenshots of 5 more fonts
@anushbhatia @smaranjitghose

**Comment by Bhavya-Sehgal** [comment]
Is there any further changes still required or is that okay ?
@anushbhatia @smaranjitghose

**Pull request merged**
