### PR TITLE
[issue #300]: Created responsive menubar for all adjustment sliders

### LINKED ISSUE #300: Design a menu bar for the Editor which can be accessed in mobile devices too. The current one just acts like a navbar
mobile_view

### PR DESCRIPTION
**Pull request by ashuvssut**
# PR Key Notes

- Created responsive and animated menubar for all adjustment sliders.
- Made necessary changes to position my menubar. It includes:
  - Removed undesired x-overflow on the whole page. (it was caused by the footer)
  - Made css changes (used display properties) to perfectly position element. (initially it was being positioned by absolute values.)

review my forked version here: https://ashuvssut.github.io/doc2pen/editor.html

closes #300

### CODE REVIEW

**Comment by smaranjitghose** [comment]
menu_bar
It should be consistent for all the options

**Comment by ashuvssut** [comment]
Okay I think I get it... you want all the content in that hamburger menu to be displayed the same way that I have created for menu bar.
Waiting for your confirmation. I will start immediately after you confirm how you actually want it 😃

**Comment by smaranjitghose** [comment]
> Okay I think I get it... you want all the content in that hamburger menu to be displayed the same way that I have created for menu bar.
> @smaranjitghose awaiting for your confirmation. I will start immediately after you confirm how you actually want it 😃

Yes

**Comment by ashuvssut** [comment]
requested changes applied.
please review

image

**Comment by smaranjitghose** [comment]
Awesome!

**Comment by ashuvssut** [comment]
My first PR merged‼️ yay

**Comment by smaranjitghose** [comment]
> My first PR merged‼️ yay😍😁

Congratutaltions @ashuvssut !

**Pull request merged**
