### PR TITLE
solved #74 : added splash screen

### PR DESCRIPTION
**Pull request by sameersrivastava13**
Added splash screen.
@anushbhatia @smaranjitghose 

splash

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> Added splash screen.
> @anushbhatia @smaranjitghose
> 
> splash

Loader takes too long!

**Comment by sameersrivastava13** [comment]
> > Added splash screen.
> > @anushbhatia @smaranjitghose
> > splash
> 
> Loader takes too long!

NO. I have tested this. As @anushbhatia said when the entire main page has loaded successfully then only loading screen should disappear.
And its working perfectly.

**Comment by anushbhatia** [comment]
change loader on all pages i  can still see previous loader on contact page

**Comment by sameersrivastava13** [comment]
> change loader on all pages i can still see previous loader on contact page

Done

**Comment by anushbhatia** [comment]
I can see the canvas loading... text it shouldn't be displayed until the loader is there

**Comment by sameersrivastava13** [comment]
> I can see the canvas loading... text it shouldn't be displayed until the loader is there

@anushbhatia can you please share a screen shot of the actual problem.
because in my case its working perfectly.

**Comment by anushbhatia** [comment]
ezgif com-video-to-gif (5)

**Pull request merged**
