### PR TITLE
Divided Editor into to halves

### PR DESCRIPTION
**Pull request by EkjotKaur**
- Changed the view of editor by dividing into two parts.
- Made Menubar Vertical for medium and large view.
- Page is responsive.
divide-pg-large
divide-pg-medium
divide-pg-small

 @smaranjitghose @anushbhatia

### CODE REVIEW

**Comment by EkjotKaur** [comment]
#60 Editor

**Comment by smaranjitghose** [comment]
@EkjotKaur Can you please have a look at the recent version and do the following changes:
- Remove the dark mode
editor
- Make sure the height and width of the two sections are equal.
- Put the menu bar above the output window. Having it one the side really looks weird😅
( Rather there should be a menu bar for both the input and output windows respectively:
    - For the input window nav bar, it makes sense to have Upload Page,Upload Font, Swtich Font Options
    - For the output window the x,y adjustments, download options)

**Comment by EkjotKaur** [comment]
Okay I'll change.

**Comment by shreyakapoor08** [comment]
Closing this PR, as it is resolved in #125

**Pull request closed without merging**
