### PR TITLE
I have added a log for the doc2pen website and embedded it in the header.

### PR DESCRIPTION
**Pull request by bhoomika07**
Screenshot 2020-12-30 at 11 01 55 PM
The header now looks something like this^^

Image of the individual logo:
doc2penlogo

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> Screenshot 2020-12-30 at 11 01 55 PM
> 
> The header now looks something like this^^
> Image of the individual logo:
> doc2penlogo

Fantastic idea for the logo Bhoomika!
You can make this a favicon too.

**Comment by smaranjitghose** [comment]
@anushbhatia can you suggest some final improvements

**Comment by smaranjitghose** [comment]
@bhoomika07 could you tell us your open source program so that we can add the labels accordingly.

**Comment by bhoomika07** [comment]
> @bhoomika07 could you tell us your open source program so that we can add the labels accordingly.

@smaranjitghose SWOC, also can you merge the pull request on 5th of Jan (rules) and I'll start working on the favicon too.

**Comment by smaranjitghose** [comment]
> > @bhoomika07 could you tell us your open source program so that we can add the labels accordingly.
> 
> @smaranjitghose SWOC, also can you merge the pull request on 5th of Jan (rules) and I'll start working on the favicon too.

Sure 😊

**Comment by anushbhatia** [comment]
This is pretty great but the logo is too cluttered. ogo should be minimal and should speak for itself not display everything in one glance
[Something like this](https://www.google.com/search?q=document+and+pen+logo&source=lnms&tbm=isch&sa=X&ved=2ahUKEwio8M7p4_jtAhVnyjgGHeZKClQQ_AUoAXoECA8QAw&biw=1536&bih=744#imgrc=WlEks3-eZ8JnvM)
 
Branding is the key to any product. So if you have a simple and a minimal logo it will be easy to understand and use it anywhere if we want to take this project on a larger scale.

**Comment by bhoomika07** [comment]
> This is pretty great but the logo is too cluttered. ogo should be minimal and should speak for itself not display everything in one glance
> [Something like this](https://www.google.com/search?q=document+and+pen+logo&source=lnms&tbm=isch&sa=X&ved=2ahUKEwio8M7p4_jtAhVnyjgGHeZKClQQ_AUoAXoECA8QAw&biw=1536&bih=744#imgrc=WlEks3-eZ8JnvM)
> 
> Branding is the key to any product. So if you have a simple and a minimal logo it will be easy to understand and use it anywhere if we want to take this project on a larger scale.

sure okay, I'll modify it

**Comment by bhoomika07** [comment]
Screenshot 2021-01-02 at 2 36 15 PM

d2p

**Comment by ashuvssut** [comment]
How is this favicon. It is free. no licence.

Pen-1320568044045688417_48

**Comment by smaranjitghose** [comment]
@bhoomika07 Could you please fix the merge conflicts

**Comment by smaranjitghose** [comment]
> How is this favicon. It is free. no licence.
> 
> download link:https://icons-for-free.com/Pen-1320568044045688417/
> 
> Pen-1320568044045688417_48
> 
> I think this is a good one because of the following reasons:
> 
> 1. It is similar to what @bhoomika07  proposed in her logo.
> 2. It is a simple icon with minimalist look.
> 3. It is available in different formats. It is available in svg format also which allows you to edit it easily.
> 4. It is available in a wide variety of resolutions.
> 5. It is free. No license required.

Although for illustrations, we don't have much talent to create them from scratch every time, as far as icons are concerned I would always suggest them to be custom built

**Comment by ashuvssut** [comment]
Ok we will not use this image.

Also I have a suggestion,

Svg images are made up of layers. Each layer have some properties like color, size, etc.

So If we choose to use the svg icon, people who know Adobe illustrator or Figma, can edit those easily. So we should use svg images.

This image download link that I gave you, has a svg variant also.

**Comment by smaranjitghose** [comment]
> Ok we will not use this image.
> 
> Also I have a suggestion,
> 
> Svg images are made up of layers. Each layer have some properties like color, size, etc.
> 
> So If we choose to use the svg icon, people who know Adobe illustrator or Figma, can edit those easily. So we should use svg images.
> 
> This image download link that I gave you, has a svg variant also.

YES, that can be done definitely

**Pull request merged**
