### PR TITLE
Controlpanel

### LINKED ISSUE #403: REACT: APP UI Update✨
Make the UI Similar to Google Docs or Microsoft Word, with the Control panel (horizontally laid out) above the text area. The text area should cover the rest of the screen as in other document or text editors
[Link to the design](https://user-images.githubusercontent.com/59422042/104116049-31e1f580-533b-11eb-8aea-dff38d6c8236.png)

### PR DESCRIPTION
**Pull request by ashuvssut**
Layout styles derived from MS Word. colors and button/input tags design derived form google docs.

----------------
Our new slider looks like as shown. 

image
**_source: google docs_**
- user can set values accurately (by directly inserting a value in it.)
- It is looks clean. 
-  And, above all, it consumes less  space in the menubar.
- These sliders are written as a **separate component** (more clean and maintainable code😁)
---------------
**Extra Feature**: added a warning dialog box that tells about the min and max value allowed on an input tag.😁😁

image
This tooltip appeared when I clicked on minus to decrease X-axis adjustment below 5. 

closes #403 

-- DWoC and SWoC participant

### CODE REVIEW

**Comment by ashuvssut** [comment]
This is the coolest issue I have ever solved. I learned about JavaScript promises and some new react lifecycle methods by cracking some bad bugs😁. 

It feels nice to solve tough stuff!

**Comment by ashuvssut** [comment]
image

**Comment by ashuvssut** [comment]
image

**Comment by anushbhatia** [comment]
@ashuvssut can you add the field for font color to this as @sanjay270899 has implemented that

**Comment by ashuvssut** [comment]
Yeah it will be done today only

**Comment by ashuvssut** [comment]
@anushbhatia, i think the page bg change was not working before. am i right sir?

**Comment by ashuvssut** [comment]
sanjay's changes cant be merged with my changes (Dropdown item's onClick event has something that not working right). I am finding a way to fix it.

**Comment by ashuvssut** [comment]
Sanjay's changes are now added. You can review the PR to merge it

**Comment by anushbhatia** [comment]
image

**Review by anushbhatia — CHANGES_REQUESTED** [review]
functions of x-axis and y-axis and font size are not working rest all function are working great work🎉✨

**Comment by ashuvssut** [comment]
i will fix this within 5 mins

**Comment by ashuvssut** [comment]
looks like when adding sanjay's changes i forgot to test my own changes if they work on not XD

**Review by smaranjitghose — APPROVED** [review]

**Comment by ashuvssut** [comment]
@anushbhatia @smaranjitghose, can you please put the **level tag for dwoc** for this feature update PR

**Pull request merged**
