### PR TITLE
Changing UI for sketch

### LINKED ISSUE #630: Changing UI for sketch
image
Moving the current pannel completely to the right so that it doesn't feel like the complete copy.

### PR DESCRIPTION
**Pull request by SalmaFarghaly**
Closes #630 

**Changes**
- moved the shapes block inside toolbox
- In code : added the "Shape" component and it's rendering in "toolbox" component and removed them from the "Canvas" component.

**Screenshots for toolbox **

**Before**
issue630before

**After**
issue630after

### CODE REVIEW

**Comment by nijin26** [comment]
Hi, @SalmaFarghaly I have a suggestion. It will be better if you can wrap 4 shapes as a second row. I mean 2 rows with 4 shapes Icon. Do you get me? Isn't it good?  🙃

**Comment by SalmaFarghaly** [comment]
@nijin26 Yes I think that will be better too, I will make it 👍

**Comment by SalmaFarghaly** [comment]
After adding the shapes on 2 rows
rowsShapes

**Comment by anushbhatia** [comment]
just resolve the conflicts will merge this

**Review by iamdarshshah — APPROVED** [review]
LGTM! 🎉

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
One minor change the mouse properties to the bottom right of the page. so that in future it doesn't affect anything.
Great work🎉🎉. Hope to see more contribution from your end

**Comment by SalmaFarghaly** [comment]
@anushbhatia Thank you so much, Great I will do it 👍

**Comment by smaranjitghose** [comment]
This PR badly messes up the background color and a couple of other options including the position coordinates.

**Pull request merged**
