### PR TITLE
Improved card structure

### LINKED ISSUE #54: Bugs
- [ ] Responsiveness
- [ ]  Card Structure

### PR DESCRIPTION
**Pull request by rutujadhanawade**
### Improved the overall card structure.
Fixes #54 
- I first experimented with couple of new card structure but at the end I finalized the original one but modified it.
- Added shadow property to the cards, colors added according to theme.
- worked on responsiveness of the card structure. 
 
s3

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@rutujadhanawade 
<p align = "center">

**Comment by smaranjitghose** [comment]
# Some quick bug fixes for you:
error_cards_1
- The next session is a bit messed up, so try to fix that
card_error
- On hovering the top left and top right edges vanish, looks quite weird 😅. Also there's a difference in the border in the bottom edges
- Try to reduce the shadow a bit

**Comment by rutujadhanawade** [comment]
- Made changes as requested.
s4

- fixed this session.
s5

**Comment by smaranjitghose** [comment]
@anushbhatia, I guess from here you can suggest more improvements!

**Pull request merged**
