### PR TITLE
Added new font

### PR DESCRIPTION
**Pull request by Mukta-Sawant**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Please read the issue description carefully

**Comment by Mukta-Sawant** [comment]
> Please read the issue description carefully 

You mean I've to add all those special characters you've given in the issue description?

**Comment by smaranjitghose** [comment]
I am sorry I would not state anything further w.r.t this issue. I have spent sufficient time to write the issue description so that these situations can be averted

**Review by anushbhatia — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Font is too light

**Pull request closed without merging**
