### PR TITLE
added react-native-snackbar

### PR DESCRIPTION
**Pull request by himanshujaidka**
while running on a local development it is showing an error of module not found, so I have added a react-native-snackbar

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
But the file isn't called anywhere how will the interpreter know the occurrence of the snack bar there. Also, do attach the screenshot and relevant information to the dependencies for it.

**Comment by himanshujaidka** [comment]
now, it is not showing any dependency error, so how could I attach a screenshot? I don't know what to do now?

**Comment by anushbhatia** [comment]
> now, it is not showing any dependency error, so how could I attach a screenshot? I don't know what to do now?

any sample video for this implementation where this has been shown

**Comment by smaranjitghose** [comment]
Please follow the contribution guidelines while raising an issue/pr

**Pull request closed without merging**
