### PR TITLE
done eslint setup and prettier

### PR DESCRIPTION
**Pull request by subhangi2731**
closes issue #947 
Changed the package.json file and done eslint setup and prettier by linting the code and using ES beautifier

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by subhangi2731** [comment]
@smaranjitghose please merge my pr

**Comment by anushbhatia** [comment]
Resolve all the indentation issues too along with this. so the deployment won't fail.

**Comment by subhangi2731** [comment]
@anushbhatia ok i will resolve this

**Comment by subhangi2731** [comment]
@anushbhatia @smaranjitghose A lot of styling eros across all *jsx files need to be fixed, along with setting custom rules for the project. Some files have "unreachable code" errors which are not styling errors, but need to be fixed. can I create an another issue please to address all these issues and errors as it is a huge one

**Comment by subhangi2731** [comment]
@smaranjitghose @anushbhatia please merge this issue and now I will create another issue to resolve and address all this errors please consider

**Comment by subhangi2731** [comment]
@smaranjitghose @anushbhatia I fixed all the errors and did the changes of the whole src folder u can check please merge now

**Comment by subhangi2731** [comment]
@smaranjitghose @anushbhatia locally all the tests are passing u can check and the conflicts are to be resolved by u so please merge my pr

**Comment by anushbhatia** [comment]
Try creating a new pr and as soon as you do it message me on discord i will merge it.

**Comment by subhangi2731** [comment]
ok @anushbhatia I will create another pr

**Comment by subhangi2731** [comment]
@anushbhatia I have closed this one and made a new pr please add the level tag to that pr which was added here

**Pull request closed without merging**
