### PR TITLE
Making favicon more user friendly.

### PR DESCRIPTION
**Pull request by CodingSpecies**
#1077 
@smaranjitghose 
I downloaded a favicon from flaticon, and changed the current one.
I couldn't get to successfully clone locally, so I uploaded the files.

Please review.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Do modify code to import this too

**Comment by CodingSpecies** [comment]
@anushbhatia do you mean update the import code, to get the icon on the page? If so, I didn't change anything apart the image itself, so the filename is still the same, so the import code would be ok too. 
Thank you.

**Comment by smaranjitghose** [comment]
Check the meta component code please

**Comment by smaranjitghose** [comment]
Also, before giving the PR, please  test the changes and attach a snapshot or clip of the same in the PR description.

**Comment by CodingSpecies** [comment]
To make PR more efficient and cleaner, I am going to close the PR, and make a new one. 
Thank you

**Pull request closed without merging**
