### PR TITLE
Improved the Form UI of the Contact Section @Home Page

### LINKED ISSUE #677: Improve the Form UI of the Contact Section @Home Page
## Requirements:

- Re-design the Contact Form

## General PR Guidelines:

- Each pull request should have an appropriate and short title like "Fixed Bug in Upload Page"

- Describe your intended changes in the description section of the pull request (Use bullet points and phrases)

- Refrain from using phrases like "Hi, I am ..", "Please merge me this OPR", "Thank You..", etc. We are only interested in technical parts

- Attach a screenshot/clip of the change(s)

- Make sure to refer to the respective issue in the respective PR using phrases like ``Resolves #issue_number or Closes #issue_number``.

- Please be patient enough. The project maintainers/mentors would review it as per their schedule. Please do not start putting comments like "Please check this" etc.

- Although we support feedback from everyone in all phases of development, it is highly advised not to put any negative comments in other participant's pull requests.

- Always keep a note of the deadline.

### PR DESCRIPTION
**Pull request by samidha28**
Fixes #677 
Changes:
- Changed the background color
- Modified placeholder text
- Modified input fields and send button styling
- Increased space between input fields 

Before:
Screenshot (182)

After:
Screenshot (179)

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Don't use the dark colour. Mono colours with some diffrenet design on it won't make it look soo dull. try making in little bit atrractive. see the dribble example that i had provided

**Comment by samidha28** [comment]
Actually, This was the bg color in the second example provided and @smaranjitghose  asked  me to remove the shapes so, I thought I had to do mono color also I'm having my exams so won't be able to contribute for few days .

**Comment by anushbhatia** [comment]
> Actually, This was the bg color in the second example provided and @smaranjitghose asked me to remove the shapes so, I thought I had to do mono color also I'm having my exams so won't be able to contribute for few days .

sure no problem you could use mono colour but adding basic shapes that match with bg won't be a problem.

**Comment by smaranjitghose** [comment]
Closed due to inactivity

**Pull request closed without merging**
