### PR TITLE
Fixed: Width Bug in the Editor (Closes #798)

### LINKED ISSUE #798: Max-Width Bug in the Editor
There is a bug in the Editor section that allows the user to increase the width of the writing section to more than what is allotted to the editing part.
The picture of the bug is attached below.
image
I can solve the issue if you could assign it to me!

### PR DESCRIPTION
**Pull request by Priyanshu-U**
closes #798 

The bug in the editor which allowed the user to increase the width to greater values than which that can be contained in the parent element has been fixed!
Before and After Images are attached below.
Before:
image
After:
Screenshot from 2021-03-29 21-25-28

### CODE REVIEW

**Comment by smaranjitghose** [comment]
editor_issue

This should not load by default

**Comment by Priyanshu-U** [comment]
> editor_issue
> 
> This should not load by default

Sir could you let me know what would be the ideal default value of width would be? So it would be easier for me to default to it.

**Comment by anushbhatia** [comment]
> > editor_issue
> > This should not load by default
> 
> Sir @smaranjitghose could you let me know what would be the ideal default value of width would be? So it would be easier for me to default to it.

It should touch the borders of the bounding box and not exceed or neither be too far from it. Just brushing.

**Comment by Priyanshu-U** [comment]
I have changed the default value of width from 65 to 70, so now not only with it not overflow but will also allow the user to decrease the value as per their own choices.

**Comment by anushbhatia** [comment]
PR not relevant. The bug is already resolved.

**Comment by N-Shar-ma** [comment]
@anushbhatia This bug is still present. I had also noticed this, hence had been waiting for this PR to get merged.
On increasing the default width from 65 to 66 here's what happens (overflow):
image

**Comment by smaranjitghose** [comment]
> @anushbhatia @smaranjitghose This bug is still present. I had also noticed this, hence had been waiting for this PR to get merged.
> On increasing the default width from 65 to 66 here's what happens (overflow):
> image

Just set the max width to 64

**Comment by Priyanshu-U** [comment]
> > @anushbhatia @smaranjitghose This bug is still present. I had also noticed this, hence had been waiting for this PR to get merged.
> > On increasing the default width from 65 to 66 here's what happens (overflow):
> > image
> 
> Just set the max width to 64

Sir what I have done is defined the width as a function so the max value would remain the current 70 and that would also make it 100% of the width

**Comment by N-Shar-ma** [comment]
This PR already solves this bug correctly, I tested the changes locally. It only needs to be merged @smaranjitghose @anushbhatia

**Comment by anushbhatia** [comment]
When you are giving such kind of PR's attach a video on it. So that we can visualize it easily and without that don't expect it to be merged. The screenshot is not that clear cause it doesn't show up on large screen devices so both for me and @smaranjitghose it didn't turn up.

**Comment by Priyanshu-U** [comment]
> When you are giving such kind of PR's attach a video on it. So that we can visualize it easily and without that don't expect it to be merged. The screenshot is not that clear cause it doesn't show up on large screen devices so both for me and @smaranjitghose it didn't turn up.

Alright sir!

**Pull request merged**
