### PR TITLE
Fixed Homepage

### PR DESCRIPTION
**Pull request by thealphacod3r**
Work Done

- Video Optimized and now is in .mp4 format

- Font Changed as Suggested

- Page Layout Changed as Suggested

Improvements

- Footer can be Improved

- Page Theme can be Improved

### CODE REVIEW

**Comment by thealphacod3r** [comment]
@smaranjitghose Please look into these changes

**Comment by smaranjitghose** [comment]
Some suggestions:
- The page is not mobile responsive
- Change the animations of the code

**Comment by thealphacod3r** [comment]
@smaranjitghose Ok

**Comment by smaranjitghose** [comment]
@thealphacod3r Separate the CSS of this page into a home.css to avoid merge conflicts of any kind

**Pull request merged**
