### PR TITLE
Sketch: Pen Color and Width

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #431 

- Feature to change Pen color and width.

sketch_pen_color_431

image

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
@sanjay270899 Nice addition!

# Some further suggestions:

- We can make the color input using hexcode rather than rgb triplets ( In normal situation, no one would care but for people from computer vision and graphics background it would be a great add on)
- We can format and prettify(I don't imply the extension) the menu/tool bar further with dedicated buttons named "Pen Color", "Pen Width", "Export"
- We can increase the canvas size slightly
- We can have a floating docker on the canvas or maybe options in the menu/tool bar for usual shapes like square, rectangle, circle, ellipse, triangle, diamond, arrow like [this](https://excalidraw.com/)
- Opacity, Stroke and Fill Settings for the shapes

In case you are taking up some or all of these do raise individual issues for them so that I can grant you points accordingly

**Comment by sanjay270899** [comment]
@smaranjitghose there is an option to enter color in hex code also.

pen_color_doc2pen

**Comment by sanjay270899** [comment]
Also, please add label for SWOC also. (Just today I got to know that I am in SWOC 😅)

**Comment by smaranjitghose** [comment]
> @smaranjitghose there is an option to enter color in hex code also.
> 
> pen_color_doc2pen

Oh, yes I missed it. My bad

**Pull request merged**
