### PR TITLE
word count and limit feature

### PR DESCRIPTION
**Pull request by himanshujaidka**

### CODE REVIEW

**Comment by himanshujaidka** [comment]
@smaranjitghose I'll work on styling later I have created a logic now. My main goal is to cover a maximum features

**Comment by smaranjitghose** [comment]
@himanshujaidka 
Good work!
- But the code is very poorly documented
- Please indent it properly ( If required use prettier extension in VS Code)
- Comment each and every section/function
- Explain your logic in comments as well
- Whenever you are importing a stylesheet or script, comment there what it is used for
- Please try to fix the merge conflicts

**Comment by himanshujaidka** [comment]
Yes please give me more time

**Comment by himanshujaidka** [comment]
@smaranjitghose done pls review it

**Pull request closed without merging**
