### PR TITLE
updated the style.css #304

### PR DESCRIPTION
**Pull request by Amit366**
The hover is kept simple with only the shadow when hovered is added.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Awesome!

**Comment by smaranjitghose** [comment]
You are in DWOC right?
Also, please reference the issue

**Comment by Amit366** [comment]
Yes sir I am in DWOC.

**Comment by Amit366** [comment]
reference the issue means should I write the issue which I solved?? 

If it is the case then :
The issue which I solved was "On hover the style of nav-items is changed".

**Comment by smaranjitghose** [comment]
> reference the issue means should I write the issue which I solved??
> 
> If it is the case then :
> The issue which I solved was "On hover the style of nav-items is changed".

Always  refer issues by typing '#' symbol

**Comment by Amit366** [comment]
I don't remember the issue number as the issue was closed today after I sent the pull request. But I think it was #303

**Comment by smaranjitghose** [comment]
> I don't remember the issue number as the issue was closed today after I sent the pull request. But I think it was #303

No worries. Do it from next time 😊

**Comment by Amit366** [comment]
Ok sir. But is it considered as one pull request in view of DWOC?

**Comment by smaranjitghose** [comment]
> Ok sir. But is it considered as one pull request in view of DWOC?

Ya.

**Comment by Amit366** [comment]
Thank you

**Pull request merged**
