### PR TITLE
updated the hover effect #299

### PR DESCRIPTION
**Pull request by Amit366**
I have updated the hover effect as suggested

### CODE REVIEW

**Comment by smaranjitghose** [comment]
navigation_bar_bug
Bug in mobile view

**Comment by Amit366** [comment]
I just added the style to the class navbar-nav.  I haven't changed anything in the main.js.

**Comment by smaranjitghose** [comment]
> I just added the style to the class navbar-nav. I haven't changed anything in the main.js.

I know, I pointed this out so that you can work on another PR related to this

**Comment by Amit366** [comment]
Sir should I create an issue regarding the hamburger problem or is the issue already created?

**Comment by smaranjitghose** [comment]
> Sir should I create an issue regarding the hamburger problem or is the issue already created?

Yes!

**Pull request merged**
