### PR TITLE
Norm-Regaular font added

### PR DESCRIPTION
**Pull request by Ankita297**
Norm Regular (TrueType)  15-04-2021 21_03_28

I have added the ttf file of the custom font  Norm-Regular font and did the required changes.
I am a GSSoC participant.

### CODE REVIEW

**Comment by Ankita297** [comment]
@anushbhatia  should i close this PR and make a new one ?
Or what should i do ?

**Comment by smaranjitghose** [comment]
> @anushbhatia should i close this PR and make a new one ?
> Or what should i do ?

Yes. Please give a new PR

**Comment by Ankita297** [comment]
Okay @smaranjitghose .

**Comment by Ankita297** [comment]
@smaranjitghose  otherwise font is okay ?

**Comment by smaranjitghose** [comment]
> @smaranjitghose otherwise font is okay ?

Yup

**Pull request closed without merging**
