### PR TITLE
added github logo

### PR DESCRIPTION
**Pull request by lopeselio**
Issue #752 
@smaranjitghose @anushbhatia , this is my pull request for the above mentioned issue assigned to me as a participant of #gssoc21 . Thank you for the opportunity
Added a github logo inside the footer to allow open source devs and contributors to navigate to the repository

- [x] Used minimal style and icon from https://feathericons.com/

### CODE REVIEW

**Comment by anushbhatia** [comment]
If you can add the animation (on loop) it would be great. just a suggestion take 2 days and let me know if you face an issue feel free to ping me on discord.

**Comment by lopeselio** [comment]
Okay that will be added

**Comment by lopeselio** [comment]
Hey I have added the animation. Making a PR

**Comment by smaranjitghose** [comment]
Please close current PR if you are continuing in a new one

**Pull request closed without merging**
