### PR TITLE
resized cards and font

### PR DESCRIPTION
**Pull request by mharshita**
@smaranjitghose sir i have resized the cards range fields and font for editor page. Please review.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir i have resized the cards range fields and font for editor page. Please review.

Reduce the size further so that all of the cards are in a single row

**Comment by smaranjitghose** [comment]
For the menu bar above, try to left align the options( currently it's right aligned)

**Comment by mharshita** [comment]
okay sir!

**Comment by mharshita** [comment]
@smaranjitghose sir please review again.

**Comment by smaranjitghose** [comment]
Download button is not working. Except that awesome efforts @mharshita !

**Comment by mharshita** [comment]
Okay sir, i will try to fix it. Thanks :)

**Pull request merged**
