### PR TITLE
added hovering effect in sketch section

### PR DESCRIPTION
**Pull request by 4kashyadav**
I have added the hovering effect in the buttons present in the sketch section!
Screenshot (533)

### CODE REVIEW

**Review by bijankundu — APPROVED** [review]
Looks good to me. Wait for project maintainers to review and merge your changes.

**Comment by smaranjitghose** [comment]
Isn't this already there? https://doc2pen.smaranjitghose.com/sketch

**Comment by bijankundu** [comment]
@smaranjitghose he added hover effect on these buttons 

image

**Comment by smaranjitghose** [comment]
> @smaranjitghose he added hover effect on these buttons
> 
> image

My bad! I see

**Pull request merged**
