### PR TITLE
2 sided view of editor and Aesthetics of the page (Issue #60)

### PR DESCRIPTION
**Pull request by Aniruddhmuley2001**
This PR is in relation to Issue #60 of the Editor.

Features of the page:
1) The page has now become responsive to an extent where it will not hinder the main image of the page downloaded.
2) In the laptop/desktop view, the editor will be divided into 2 parts, one where the required changes will be done, and the other where the changes will be visible.
3) The buttons have been aesthetically styled, following the principles of Soft UI, a modern styling UI/UX trend.

### CODE REVIEW

**Comment by anushbhatia** [comment]
resolve the merge conflicts

**Comment by Aniruddhmuley2001** [comment]
Done @anushbatia

**Comment by Aniruddhmuley2001** [comment]
@anushbhatia Conflicts resolved. Please do review this.

**Comment by smaranjitghose** [comment]
UI_messed_up
The complete layout seems to be messed up.
I am closing this PR @Aniruddhmuley2001. Let @EkjotKaur do the basic 2 side layout. You take over with the UI enhancements

**Comment by Aniruddhmuley2001** [comment]
@smaranjitghose will you please tell me what design was expected? Below is the one made in this PR.
Doc2Pen editor v4

**Comment by Aniruddhmuley2001** [comment]
@smaranjitghose Required changes have been made, conflicts merged. Thank you!

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Doc2Pen _ Editor and 2 more pages - Personal - Microsoft​ Edge 30-08-2020 12_38_41

**Comment by Aniruddhmuley2001** [comment]
@anushbhatia Please check if the changes are made as required.

**Pull request merged**
