### PR TITLE
Feature to Load Images from Local System on Sketch Page

### PR DESCRIPTION
**Pull request by Chaitanya31612**
https://user-images.githubusercontent.com/54992097/113013654-83ab5680-9199-11eb-9955-d6e317b477fd.mp4

### CODE REVIEW

**Comment by Chaitanya31612** [comment]
The image is getting uploaded on screen but then after some time I am getting this error

image

I have not worked with canvas so don't know about it.
Help needed.

**Comment by anushbhatia** [comment]
https://stackoverflow.com/questions/18947556/typeerror-cannot-read-property-0-from-undefined#:~:text=Looks%20like%20what%20you're,in%20your%20'data'%20array.&text=This%20will%20cause%20you%20to,is%20equal%20to%20'name'.
I think the issue is entering balues of the array manually. Try reading through this approach u might find something

**Comment by Chaitanya31612** [comment]
It is giving that error in this renderer.js file of roughjs module. Maybe when the image is placed on the screen it creates problem with the offset and coordinates of the canvas. 

image

image


Sometimes it works fine and other times give this error and disturbs the pointer coordinates. How can I fix this?

**Review by anushbhatia — COMMENTED** [review]
for value equla 0 in the array handle the conditon
```
for(var iIndex = 1; iIndex <= data.length; iIndex++){
    if (data[iIndex][0] === name){
         break;
    };
    Logger.log(data[i][0]);
 };
```

**Comment by Chaitanya31612** [comment]
> for value equla 0 in the array handle the conditon
> 
> ```
> for(var iIndex = 1; iIndex <= data.length; iIndex++){
>     if (data[iIndex][0] === name){
>          break;
>     };
>     Logger.log(data[i][0]);
>  };
> ```

But that is in a node module package and I can't change it.

**Pull request closed without merging**
