### PR TITLE
issue #330 fixed

### LINKED ISSUE #330: Drop Down menu is  For Download alignment Problem
Screenshot (505)

Hope It helps
I want to work on this issue as a part of DevScript Winter of Code 2020 so please assign this to me

### PR DESCRIPTION
**Pull request by ashuvssut**
review link: https://ashuvssut.github.io/doc2pen/editor.html

closes #330

### CODE REVIEW

**Comment by anushbhatia** [comment]
https://user-images.githubusercontent.com/40017559/103473092-b1f7e080-4dba-11eb-83ee-c7a7f9f3f43c.mp4
See the margin if you can resolve this it would be great.

**Comment by ashuvssut** [comment]
review link: https://ashuvssut.github.io/doc2pen/editor.html

changes will reflect shortly

**Review by smaranjitghose — APPROVED** [review]

**Review by anushbhatia — APPROVED** [review]

**Comment by ashuvssut** [comment]
This pr is not merged yet, are there any issues in this pr?

**Comment by smaranjitghose** [comment]
> This pr is not merged yet, are there any issues in this pr?

Had some merge conflicts lately

**Comment by ashuvssut** [comment]
Ok sir😅

**Pull request merged**
