### PR TITLE
added word count feature

### PR DESCRIPTION
**Pull request by himanshujaidka**
solved issue #183

### CODE REVIEW

**Comment by himanshujaidka** [comment]
Screenshot (88)

**Comment by smaranjitghose** [comment]
> solved issue #183

Please position it according to the sketch given

**Comment by smaranjitghose** [comment]
Only No of words left is working, the word count itself is not working

**Comment by himanshujaidka** [comment]
changes done

**Comment by himanshujaidka** [comment]
Thanks @smaranjitghose and @anushbhatia

**Pull request merged**
