### PR TITLE
Fix Editor Page Wrong Position Bug

### LINKED ISSUE #1043: Major Bug in Editor Page
Bug_in_editor_page

Due to some recent PRs, the functioning of the editor page is broken. From entering text to saving the file, nothing is accessible

### PR DESCRIPTION
**Pull request by N-Shar-ma**
This should fix #1043 (could not test thoroughly due to technical issues my side)

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
The preview deployment works perfectly!

**Comment by ashuvssut** [comment]
This Problem was fixed and does not exist now

**Comment by N-Shar-ma** [comment]
> This Problem was fixed and does not exist now
> 
> do a pull to update and see the Editor page.

I know, but when I had made this PR, this was a critical bug and no PR before mine solved this.
Should I close this myself?

**Comment by smaranjitghose** [comment]
@N-Shar-ma @ashuvssut  Thanks a lot for your overall contribution to the project. Do let me know if I can help out with writing any recommendation for you on LinkedIn or anything else. All the best for your future endeavors. In case, you wanted to stick longer, this project is also a part of LGSOC'21

**Comment by N-Shar-ma** [comment]
> @N-Shar-ma @ashuvssut Thanks a lot for your overall contribution to the project. Do let me know if I can help out with writing any recommendation for you on LinkedIn or anything else. All the best for your future endeavors. In case, you wanted to stick longer, this project is also a part of LGSOC'21

Yes Sir, a LinkedIn recommendation would be wonderful, thank you so much! 
My LinkedIn profile link is: https://in.linkedin.com/in/nehal-sharma-55998b205

**Pull request closed without merging**
