### PR TITLE
width and linespacing: done. Extra feature😁😁: Letterspacing

### LINKED ISSUE #372: REACT: Adding Line spacing and Width 📑
Line Spacing between two elements.
Width of the number of words in a line. It can be done by adding a slider just like that specified in the image.
***Bonus**
Adding letter Spacing. Space between two letters in a word.
image

### PR DESCRIPTION
**Pull request by ashuvssut**
resolves #372 

Both width and linespacing are present

Extra feature: Letterspacing😁😁

image

image above shows width and letterspacing

-- DWoC and SWoC participant

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Decrease step size. Rest works fine

**Review by smaranjitghose — CHANGES_REQUESTED** [review]
Reduce step size. Rest is cool!

**Comment by ashuvssut** [comment]
Sir, step size?

which one sir😅

**Comment by smaranjitghose** [comment]
> Sir, step size?
> 
> which one sir😅

I mean if you are going from 0-10, instead of incrementing with 1 do an increment of 0.5. Increments in letter spacing needs to be more precise as compared to other options

**Comment by ashuvssut** [comment]
ok sir

**Comment by ashuvssut** [comment]
@smaranjitghose  feature added: I have added the code to set the step size.

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
