### PR TITLE
preloader implemented

### LINKED ISSUE #424: Implement a Cool Preloader
I wan to implement a cool preloader that i am working right now. It will always appear when pages load. 

It will use just some **simple** css animation😁. NO gif or svg.

would take one day at max

### PR DESCRIPTION
**Pull request by ashuvssut**
Preview : https://vimeo.com/user132135983/review/504920987/2aa26c23d2

Only CSS used.

closes #424

-- (DWoC and SWoC Participant)

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
It shows both the axis when it starts loading on my screen. Keep the colour of the loader blue

**Comment by ashuvssut** [comment]
@anushbhatia  please elaborate. you dont want background colors to change?

**Review by anushbhatia — COMMENTED** [review]
#4285F4 use this colour for the background

**Comment by ashuvssut** [comment]
I am a DWoC and SWoC participant. please add the relevant tags to this PR for the both evnets

**Comment by smaranjitghose** [comment]
Please do a SQUASH commit whenever you incorporate changes 🙏🙏

**Comment by smaranjitghose** [comment]
The current pre-loader is too basic.
use codepen for some inspiration!

**Pull request merged**
