### PR TITLE
#63 UI/UX Updates

### PR DESCRIPTION
**Pull request by imPGupta**
Background colour changed and UI improved and added animated github icon

Screenshot (75)

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://demos.creative-tim.com/material-kit/index.html
have something minimal like this.
the current navbar looks really bad

**Comment by smaranjitghose** [comment]
@imPGupta Any updates?

**Comment by imPGupta** [comment]
@anushbhatia  Can I add Home, Editor and Team pages link in the Footer or not.

**Comment by smaranjitghose** [comment]
> @anushbhatia Can I add Home, Editor and Team pages link in the Footer or not.

I guess it;s not required in the footer since we already have it in the navbar. The footer for all the pages can be kept simple and minimal. We have a small product focussed on helping students. That's our entire work. We don't have much to tell people about

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Use a better GitHub logo for that because that looks really weird on hover https://useanimations.com/ u can use this

**Comment by imPGupta** [comment]
@anushbhatia  Added animated github icon

**Comment by anushbhatia** [comment]
Resolve the conflicts and make the text bold

**Comment by imPGupta** [comment]
@anushbhatia conflicts resolved

**Comment by anushbhatia** [comment]
https://deploy-preview-112--doc2pen.netlify.app/editor.html look through this page your footer shifts to the left of the page

**Comment by imPGupta** [comment]
This is due to my github repo is not updated with latest commits. So if you merge this commit then I will updated my repo and then I will correct footer in editor page.

**Comment by anushbhatia** [comment]
Also, don't keep the text in red below https://girlscriptboilerplate.netlify.app/ you can have something simple like that

**Comment by imPGupta** [comment]
Can I make it to the text colour of "Why wait more"  line in index.html?

**Comment by anushbhatia** [comment]
yes

**Comment by imPGupta** [comment]
I am going to create a new PR to resolve all merge conflicts.

**Pull request closed without merging**
