### PR TITLE
Improved Heading Styles on Contact Page

### PR DESCRIPTION
**Pull request by N-Shar-ma**
I've updated the heading styles to make it look more like a heading and less like a button, for better user experience

### Before :
image

### After : 
image

### CODE REVIEW

**Comment by anushbhatia** [comment]
This change isn't useful as the button should be visible and easy to use.

**Comment by N-Shar-ma** [comment]
@anushbhatia Sir the point of this PR is that the heading is not a button. It was styled like a button but it is simply a heading. Nothing happens on clicking the heading, and hence I changed the style so it does not look like a button and confuse the user.
I would be grateful if you could again review this PR.
Thank you!

**Comment by smaranjitghose** [comment]
> @anushbhatia Sir the point of this PR is that the heading is not a button. It was styled like a button but it is simply a heading. Nothing happens on clicking the heading, and hence I changed the style so it does not look like a button and confuse the user. Please refer to the issue this PR solves: #588
> I would be grateful if you could again review this PR.
> Thank you!

Could you please remove the button/heading completely. I guess we don't need it at all since the user would arrive on the page after clicking Contact on the navbar

**Comment by N-Shar-ma** [comment]
Sure Sir, I'll do that. Should I create a new PR for that? Or continue here?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Sure Sir, I'll do that. Should I create a new PR for that? Or continue here?

Create a new PR

**Pull request closed without merging**
