### PR TITLE
Readme open src upd

### LINKED ISSUE #495: update opensource section
add jwoc gssoc crosswoc mwoc in the opensource section

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #495 

---------

_--I have participated in DWoC SWoC and MWoC_

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@ashuvssut I am currently insisting on contributions to the direct codebase of the project rather than small documentation changes. So for the sake of fair treatment, I would request you to put this commit with some other PR of yours. I hope you understand😊

**Comment by ashuvssut** [comment]
in `./assets` folder :--

- https://github.com/smaranjitghose/doc2pen/blob/master/assets/js/main.js
- and 2 old logos:
   https://github.com/smaranjitghose/doc2pen/tree/master/assets/images

these file is looks useless. its used nowhere. What should I do with them?

**Comment by smaranjitghose** [comment]
> in `./assets` folder :--
> 
> * https://github.com/smaranjitghose/doc2pen/blob/master/assets/js/main.js
> * and 2 old logos:
>   https://github.com/smaranjitghose/doc2pen/tree/master/assets/images
> 
> these files is look useless. its used nowhere. What should I do with them?

Umm. Remove them and give as a squashed commit in this PR. I'll merge it as a single change with the README changes

**Review by smaranjitghose — APPROVED** [review]

**Comment by ashuvssut** [comment]
actually I havent squash committed it. I have converted a few png to webp too. but the PR is merged and closed😅.

Ok now worries, I will give those images through my next PR.

**Comment by ashuvssut** [comment]
@smaranjitghose  I was unable to register for CrossWoC coz its participation form closed 4days ago.

And therefore you dont need to put CrossWoC label😄

**Comment by smaranjitghose** [comment]
> @smaranjitghose I was unable to register for CrossWoC coz its participation form closed 4days ago.
> 
> And therefore you dont need to put CrossWoC label😄

Oh, I was not aware of it

**Pull request merged**
