### PR TITLE
Slider positioning added

### PR DESCRIPTION
**Pull request by carbseater**
I added the positioning of X and Y slider according to UI,
Now it looks like this
Capture

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Please have a look at what I had suggested for the UI. This does not meet the requirements

**Comment by carbseater** [comment]
> Please have a look at what I had suggested for the UI. This does not meet the requirements

Where do you have suggested the UI ? I'm new on github

**Comment by smaranjitghose** [comment]
> > Please have a look at what I had suggested for the UI. This does not meet the requirements
> 
> Where do you have suggested the UI ? I'm new on github

I have pasted it in the issue corresponding to this PR

**Comment by carbseater** [comment]
> > > Please have a look at what I had suggested for the UI. This does not meet the requirements
> > 
> > 
> > Where do you have suggested the UI ? I'm new on github
> 
> I have pasted it in the issue corresponding to this PR

I couldn't able to find the suggestion, there is no linked issues in reviews ? Where can i exactly find the suggestions @smaranjitghose

**Comment by smaranjitghose** [comment]
> > > > Please have a look at what I had suggested for the UI. This does not meet the requirements
> > > 
> > > 
> > > Where do you have suggested the UI ? I'm new on github
> > 
> > 
> > I have pasted it in the issue corresponding to this PR
> 
> I couldn't able to find the suggestion, there is no linked issues in reviews ? Where can i exactly find the suggestions @smaranjitghose

Here you go brother:
https://user-images.githubusercontent.com/46641503/103203033-0eba4d80-491a-11eb-92ea-d1e9d5bdc6b1.png

**Comment by carbseater** [comment]
Does this picture means , the x-axis slider on extreme right and above the output and y-axis slider in bottom-left of output? @smaranjitghose 

> > > > > Please have a look at what I had suggested for the UI. This does not meet the requirements
> > > > 
> > > > 
> > > > Where do you have suggested the UI ? I'm new on github
> > > 
> > > 
> > > I have pasted it in the issue corresponding to this PR
> > 
> > 
> > I couldn't able to find the suggestion, there is no linked issues in reviews ? Where can i exactly find the suggestions @smaranjitghose
> 
> Here you go brother:
> https://user-images.githubusercontent.com/46641503/103203033-0eba4d80-491a-11eb-92ea-d1e9d5bdc6b1.png

Does this picture means , the x-axis slider on extreme right and above the output and y-axis slider in bottom-left of output? @smaranjitghose

**Comment by smaranjitghose** [comment]
> Does this picture means , the x-axis slider on extreme right and above the output and y-axis slider in bottom-left of output? @smaranjitghose
> 
> > > > > > Please have a look at what I had suggested for the UI. This does not meet the requirements
> > > > > 
> > > > > 
> > > > > Where do you have suggested the UI ? I'm new on github
> > > > 
> > > > 
> > > > I have pasted it in the issue corresponding to this PR
> > > 
> > > 
> > > I couldn't able to find the suggestion, there is no linked issues in reviews ? Where can i exactly find the suggestions @smaranjitghose
> > 
> > 
> > Here you go brother:
> > https://user-images.githubusercontent.com/46641503/103203033-0eba4d80-491a-11eb-92ea-d1e9d5bdc6b1.png
> 
> Does this picture means , the x-axis slider on extreme right and above the output and y-axis slider in bottom-left of output? @smaranjitghose

Yes

**Pull request closed without merging**
