### PR TITLE
Project init

### LINKED ISSUE #407: Implement React Code Splitting to improve page loadtime
refer [here](https://reactjs.org/docs/code-splitting.html) to react code splitting examples.

In Code splitting User only downloads the files related to the page he is visiting instead of loading the entire site's files.
It improves loadtime in react

Right now this app has just one page. so code splitting is not required. But, I will implement code splitting so that in future contributors can add pages that will have this code splitting.

I want to work on this feature. Please assign me this.

--(DWoC and SWoC Participant)

### PR DESCRIPTION
**Pull request by ashuvssut**
- defined routes to pages
- code-splitting implemented
- worked on file structure
- provided documentation in Project_Structure.md file about file structure

closes #407

### CODE REVIEW

**Comment by ashuvssut** [comment]
after this gets merge I can make the Editor page using reusable components(like sliders are used more than one once which opens an opportunity to make a resusable component)

**Comment by ashuvssut** [comment]
I am sure that this file structure makes the code more organized and less confusing. for example: components related to only a single page are put in that page directory's level component folder instead of project level component folder (in `src` folder).  people now dont need to find their component related to a page in project level components folder because instead of putting all the components in the project level component folder it is present in its page level component folder.

I lea

**Comment by ashuvssut** [comment]
sir please consider my PR for DWOC. I am currently working to improve my DWoC ranking. i am currently ranked19😐. Just making a good linkedin profile😅

**Comment by ashuvssut** [comment]
@smaranjitghose. Sir, the last commit fixed a deployment error. but another deployment error showed up. It is given below.

`
remote: Permission to smaranjitghose/doc2pen.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/smaranjitghose/doc2pen/': The requested URL returned error: 403
Error: Process completed with exit code 128.
`
Is there some fault in my code or is this some bug. Can you please tell me about this. I will try to avoid that mistake in my next PRs.

**Comment by smaranjitghose** [comment]
> @smaranjitghose. Sir, please consider my PR for DWOC. I am currently working to improve my DWoC ranking. I am currently ranked19😐.
> 
> I am Just trying make a good linkedin profile😅.

Do not write these messages. I would give a poor impression for both you and me. Just request the labels, either me and @anushbhatia will definitely give that.  __Delete that message too__

**Comment by ashuvssut** [comment]
> > @smaranjitghose. Sir, please consider my PR for DWOC. I am currently working to improve my DWoC ranking. I am currently ranked19😐.
> > I am Just trying make a good linkedin profile😅.
> 
> Do not write these messages. I would give a poor impression for both you and me. Just request the labels, either me and @anushbhatia will definitely give that. **Delete that message too**

ok sir😅.

**Pull request merged**
