### PR TITLE
Routing/418

### LINKED ISSUE #418: REACT: Enable Routing 📍
Implementing Routing
1. Adding homepage as a default page in when opened.
2. Making the navbar to move down on different sections.

### PR DESCRIPTION
**Pull request by sanjay270899**
Close #418 

- Home Page (Default Page) Path = '/'
- Editor Path = '/editor'

Header when the path is '/'
image

Header when the path is '/editor'
image

GIF:
doc2pen

### CODE REVIEW

**Comment by sanjay270899** [comment]
@anushbhatia @smaranjitghose Let me know if any changes needed. Thank you!

**Comment by anushbhatia** [comment]
Great Work @sanjay270899 Keep it up✨✨✨

**Comment by smaranjitghose** [comment]
@sanjay270899 are you in SWoC as well?

**Comment by sanjay270899** [comment]
@smaranjitghose No. I have participated only in DWOC.

**Pull request merged**
