### PR TITLE
Create Contribution.MD

### PR DESCRIPTION
**Pull request by ritiksoni00**
#126 
in readme I should link it ??

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
This is code of conduct please take care about it and https://github.com/smaranjitghose/girlscript_chennai_website/blob/master/CONTRIBUTING.md
refer this 
add gifs
marking scheme etc

**Comment by ritiksoni00** [comment]
label it first, please

**Comment by ritiksoni00** [comment]
Sorry my bad!

**Comment by ritiksoni00** [comment]
@anushbhatia

**Comment by smaranjitghose** [comment]
These are the things that I would appreciate you submit in the last hours of the soc. Please focus now on contributing to the actual codebase

**Pull request closed without merging**
