### PR TITLE
Removed Head Body Distinction in Editor

### LINKED ISSUE #769: Remove Title,Body @Editor Page
## Sample Snapshot

title_body

## Description

At the current stage of the project, it does not make much sense to have separate options for title and body. Revamp the functions so that one can simply start entering text into the document without the already existing distinction of title and body

### PR DESCRIPTION
**Pull request by N-Shar-ma**
# Closes #769 

## Major Changes in Codebase:

- Removed the title tab and body tab elements in the Control Panel of the Editor Page
- Removed the title element and made the body element take up 100% of the space for the document
- Removed functions that are now not needed, like `isBody` and `isBodyHandler` from the `editContext.js`
- Removed Head Styling options from the `editContext.js`

## Minor Changes:

- Removed styling for elements that were removed
- Replaced all checks for `isBody` with the code intended for body only

## Before Screenshot:
image

## After Screenshot:
image

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@N-Shar-ma Nice work.

Could you please pull the recent changes to the Editor Page, incorporate them into your PR and give a squash commit

**Comment by N-Shar-ma** [comment]
I'm sorry, I tried my best to squash all the commits after pulling from upstream/master and resolving merge conflicts, but it seems something went wrong. 
Till commit #b90b905 everything was fine, but I guess I messed up the squashing part. Sorry again!

**Comment by N-Shar-ma** [comment]
I reverted this branch to the one with all my changes and with all the recent changes pulled and conflicts resolved.
Sorry for the inconvenience!

**Comment by smaranjitghose** [comment]
> I reverted this branch to the one with all my changes and with all the recent changes pulled and conflicts resolved.
> Sorry for the inconvenience!

No worries!.. Good Job @N-Shar-ma

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
