### PR TITLE
"generating pdf toast implemented"

### LINKED ISSUE #580: 'generating pdf...🔄🔄' notification
Currently the PDF takes about 5-6secs to generate.

For that small interval a popup must come up saying
"Generating PDF. please wait..."

I am a GSSOC particpant. I want to work on this.

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #580 

chrome-capture (2)

-----------------------------

_- I have participated in GSSOC_

### CODE REVIEW

**Comment by nijin26** [comment]
That's really a cool toast, @ashuvssut 😍

**Comment by smaranjitghose** [comment]
> closes #580
> 
> chrome-capture (2)
> 
> _- I have participated in GSSOC_

Nice work, the only issue is the option to save the pdf pops up several seconds after the "generating pdf toast" is over. So we need to adjust the delay accordingly

**Comment by ashuvssut** [comment]
I have removed the timer

Now I am using JS `Promise` in an `async` function to wait for the generation of the PDF to complete... after waiting I have put commands to close the popup
so there is no need for a timer now

**Comment by ashuvssut** [comment]
can you put [here](https://github.com/smaranjitghose/doc2pen/pull/603) relevant level labels for GSSOC too?😄

**Pull request merged**
