### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by himanshujaidka**
New footer design for index.html

### CODE REVIEW

**Comment by anushbhatia** [comment]
Try using this [https://materializecss.com/footer.html](https://materializecss.com/footer.html)

**Comment by himanshujaidka** [comment]
Means I have to change footer?

**Comment by himanshujaidka** [comment]
Screenshot (45)

**Comment by himanshujaidka** [comment]
new footer @anushbhatia as you suggested

**Comment by anushbhatia** [comment]
add relevant content add white colour to it

**Comment by himanshujaidka** [comment]
Screenshot (46)

**Comment by smaranjitghose** [comment]
Please fix the merge conflict

**Comment by himanshujaidka** [comment]
done @smaranjitghose

**Pull request merged**
