### PR TITLE
Added font-size select button in nav-bar

### PR DESCRIPTION
**Pull request by dipanshparmar**
# Added font-size select button in nav-bar
Font-size select options is now available in the second nav-bar itself instead of the page body.

### Types of changes:
1. Code formatting
2. Changes are well commented so that other developers can easily work on the issues

## Before
Font size selector was in page body.
image

## After 
Font size selctor is now in second nav-bar
image
image

It will resolve issue #197

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@smaranjitghose Please have a look. This PR will close #197

**Comment by smaranjitghose** [comment]
@dipanshparmar are you a part of SLOP program?

**Comment by rutujadhanawade** [comment]
@smaranjitghose What is SLOP program? Can plz tell me about it.

**Comment by dipanshparmar** [comment]
> @dipanshparmar are you a part of SLOP program?

Nope! I don't really know what it is 😅

**Comment by smaranjitghose** [comment]
> @smaranjitghose What is the SLOP program? Can you plz tell me about it?

Hey Rutuja! 
Well SLOP is a 2-month open-source program for beginners to get started with open-source which is organized by the DSC DAIICT.

Their website is: https://slop.dscdaiict.in/
The projects available for contribution are: https://slop.dscdaiict.in/projects
( I am mentoring and maintaining 5 projects here)

**Comment by smaranjitghose** [comment]
> > @dipanshparmar are you a part of SLOP program?
> 
> Nope! I don't really know what it is 😅

Cool. No issues

**Comment by rutujadhanawade** [comment]
Thanks @smaranjitghose . I am little late now..! 😅

**Comment by smaranjitghose** [comment]
> Thanks @smaranjitghose . I am little late now..! 😅

No worries. There a lot of similar open-source programs coming up. I'll let you know

**Comment by rutujadhanawade** [comment]
@smaranjitghose yeah thanks.

**Pull request merged**
