### PR TITLE
Tech Stacks added

### PR DESCRIPTION
**Pull request by RaveenaBhasin**
Added the technologies used in the project

### CODE REVIEW

**Comment by anushbhatia** [comment]
if you colud add reactjs that would be more specific

**Comment by smaranjitghose** [comment]
@RaveenaBhasin Please follow the contribution guidelines for the PR.

Issue Reference?
Snapshot?

**Comment by smaranjitghose** [comment]
> if you colud add reactjs that would be more specific

I believe we can make it React, Netlify(the deploy badge), p5.js? What do you think @anushbhatia ?

**Comment by anushbhatia** [comment]
> > if you colud add reactjs that would be more specific
> 
> I believe we can make it React, Netlify(the deploy badge), p5.js? What do you think @anushbhatia ?

Yess it would be great.

**Comment by RaveenaBhasin** [comment]
@anushbhatia @smaranjitghose So do I need to add reactjs in place of js anything else I have to add?

**Comment by anushbhatia** [comment]
> @anushbhatia @smaranjitghose So do I need to add reactjs in place of js anything else I have to add?

remove css and add scss instead of that. 
1.html
2.scss
3.js
4.reactjs.

**Comment by RaveenaBhasin** [comment]
Screenshot (1580)

**Comment by RaveenaBhasin** [comment]
@smaranjitghose Please review it

**Review by iamdarshshah — CHANGES_REQUESTED** [review]
@RaveenaBhasin Please remove `CSS` badge & add `scss` badge instead.

**Comment by smaranjitghose** [comment]
This PR is taking way more than required!

**Pull request closed without merging**
