### PR TITLE
[feature] dynamic title

### LINKED ISSUE #519: Dynamic Page Titles
[Reference](https://medium.com/@alperen.talaslioglu/changing-page-title-dynamically-when-user-changes-tab-5d372554377c)

The above reference is well detailed. Please go through it carefully if you wish to contribute to this.

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #519 

- dynamic title has attention message : "come back"
--------------
_--I have participated in DWoC SWoC and MWoC_

### CODE REVIEW

**Comment by smaranjitghose** [comment]
# Some slight modifications:

- The text should be ``Come back``
- Replace the favicon with 🙏 when the above message is blinked

**Comment by smaranjitghose** [comment]
You can give the same PR for the other project too as there is a similar issue there as well

**Comment by ashuvssut** [comment]
@smaranjitghose it would be great if you could add labels for `DWoC` in all my unmerged PRs

**Comment by smaranjitghose** [comment]
> 
> 
> @smaranjitghose it would be great if you could add labels for only `DWoC` in my unmerged PRs

Can you paste the links please

**Comment by ashuvssut** [comment]
https://github.com/smaranjitghose/doc2pen/pull/549

https://github.com/smaranjitghose/doc2pen/pull/554

**Pull request merged**
