### PR TITLE
Added Poppins to the "Editor" page

### PR DESCRIPTION
**Pull request by dipanshparmar**
# Added Poppins font

## Before
image
(No Poppins)

## After
image
(Poppins)
image

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@smaranjitghose This PR will close #194

**Comment by smaranjitghose** [comment]
> @smaranjitghose This PR will close #194

Download the Poppins font file and add it to the assets folder as well

**Comment by dipanshparmar** [comment]
yeah! done
image

**Comment by dipanshparmar** [comment]
> > @smaranjitghose This PR will close #194
> 
> Download the Poppins font file and add it to the assets folder as well

yeah! done
image

**Comment by smaranjitghose** [comment]
Please have a look at your PR's deploy and fix the bugs: https://deploy-preview-219--doc2pen.netlify.app/editor.html

**Comment by dipanshparmar** [comment]
@smaranjitghose I'm closing this PR. Sending a new one.

**Pull request closed without merging**
