### PR TITLE
alignment fixed

### LINKED ISSUE #471: misaligned navbar link to 'Sketch'
image

I want to work on this

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #471 

image

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by ashuvssut** [comment]
I have participated in DWoC SWoC and MWoC

**Comment by smaranjitghose** [comment]
@ashuvssut if you are in MWOC, for updation of scores remind me next week

**Comment by ashuvssut** [comment]
ok sir

**Comment by smaranjitghose** [comment]
> ok sir

Updated

**Comment by sanjay270899** [comment]
@ashuvssut 😅
image

**Comment by ashuvssut** [comment]
okay I will  increase its width. n add some right margin.

@sanjay270899  what do you say?

**Pull request merged**
